/**
 * Food & Cafe Guide - Hanoi Edition
 * Dữ liệu quán ăn & quán cà phê tuyển chọn tại Hà Nội
 * Đạt chuẩn chất lượng: Đánh giá >= 4.0★ và Lượt review >= 100+ trên Google Maps
 */

const INITIAL_CATEGORIES = [
  {
    id: "all",
    name: "Tất cả",
    icon: "🍽️",
    description: "Tất cả quán ăn & cà phê trong cẩm nang",
    count: 0
  },
  {
    id: "cafe-chill",
    name: "Cà phê & Trà",
    icon: "☕",
    description: "Cafe view đẹp, cafe trứng truyền thống, góc học tập & làm việc chill (>=4.0★, >=100 đánh giá)",
    mapsUrl: "https://www.google.com/maps/search/cafe+chill+ha+noi"
  },
  {
    id: "mon-soi",
    name: "Món sợi (Phở, Bún, Mì)",
    icon: "🍜",
    description: "Phở bò truyền thống, bún chả, bún riêu, miến lươn chuẩn vị Hà Thành",
    mapsUrl: "https://www.google.com/maps/search/pho+bun+mien+ha+noi"
  },
  {
    id: "com-xoi",
    name: "Cơm & Xôi",
    icon: "🍚",
    description: "Xôi xéo thơm nức, cơm rang dưa bò, cơm tấm sườn nướng",
    mapsUrl: "https://www.google.com/maps/search/xoi+com+ha+noi"
  },
  {
    id: "banh-mi-cuon",
    name: "Bánh mì & Đồ cuốn",
    icon: "🥖",
    description: "Bánh mì phố cổ, phở cuốn Ngũ Xã, bánh cuốn nóng hổi",
    mapsUrl: "https://www.google.com/maps/search/banh+mi+pho+cuon+ha+noi"
  },
  {
    id: "lau-nuong",
    name: "Lẩu & Nướng",
    icon: "🥩",
    description: "Lẩu ếch măng cay, nướng ngói vỉa hè, lẩu riêu cua bắp bò",
    mapsUrl: "https://www.google.com/maps/search/lau+nuong+ha+noi"
  },
  {
    id: "an-vat",
    name: "Ăn vặt & Tráng miệng",
    icon: "🍧",
    description: "Nộm bò khô, nem chua rán, chè khúc bạch, tào phớ thanh mát",
    mapsUrl: "https://www.google.com/maps/search/an+vat+ha+noi"
  },
  {
    id: "do-a-au",
    name: "Đồ Nhật, Hàn & Á Âu",
    icon: "🍣",
    description: "Bít tết bò chảo gang, sushi tươi ngon, pizza nướng củi, mì Ý",
    mapsUrl: "https://www.google.com/maps/search/nha+hang+nhat+han+ha+noi"
  },
  {
    id: "quan-nhau",
    name: "Quán nhậu & Đêm",
    icon: "🍻",
    description: "Bia hơi vỉa hè, nhậu lai rai, ẩm thực phố đêm không ngủ",
    mapsUrl: "https://www.google.com/maps/search/quan+nhau+bia+dem+ha+noi"
  }
];

const INITIAL_PLACES = [
  // ==========================================
  // ☕ TOP QUÁN CAFE HÀ NỘI (>= 4.0★ & >= 100 REVIEWS)
  // CẦU GIẤY, BA ĐÌNH, HOÀN KIẾM, ĐỐNG ĐA, TÂY HỒ
  // ==========================================
  {
    id: "cafe-1",
    name: "Cafe Giảng - Cà Phê Trứng 1946",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "39 Nguyễn Hữu Huân, Lý Thái Tổ, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cafe+Giang+39+Nguyen+Huu+Huan+Ha+Noi",
    rating: 4.5,
    reviewCount: 12500,
    priceRange: "25.000đ - 45.000đ",
    priceLevel: "low",
    time: "07:00 - 22:30",
    mustTry: "Cà phê trứng nóng / Cacao trứng ngậy / Cà phê trứng đá",
    review: "Nơi khai sinh ra món cà phê trứng huyền thoại của Hà Nội từ năm 1946. Kem trứng đánh bông mịn như lụa, béo ngậy thơm lừng hòa quyện cùng cà phê phin đậm đặc.",
    tags: ["Cafe trứng", "Phố Cổ", "Lâu đời", "Huyền thoại"],
    vibe: ["Truyền thống", "Khách du lịch", "Check-in"],
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-2",
    name: "The Note Coffee - View Hồ Gươm",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "64 Lương Văn Can, Hàng Trống, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=The+Note+Coffee+64+Luong+Van+Can+Ha+Noi",
    rating: 4.8,
    reviewCount: 15200,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "06:30 - 23:00",
    mustTry: "Cà phê cốt dừa béo ngậy / Trà đào cam sả / Latte",
    review: "Quán cafe độc đáo bậc nhất với hàng triệu mảnh giấy note sắc màu dán kín từ trần đến tường do du khách khắp thế giới để lại. View tầng 3-4 nhìn trọn vẹn Hồ Gươm tuyệt đẹp.",
    tags: ["View Hồ Gươm", "Giấy Note", "Nổi tiếng thế giới", "Check-in"],
    vibe: ["Check-in", "Hẹn hò", "Khách du lịch"],
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-3",
    name: "Cafe Đinh - Gác Cổ Hồ Gươm",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "13 Đinh Tiên Hoàng, Hàng Bạc, Hoàn Kiếm, Hà Nội (Tầng 2)",
    mapsUrl: "https://maps.google.com/?q=Cafe+Dinh+13+Dinh+Tien+Hoang+Ha+Noi",
    rating: 4.6,
    reviewCount: 2600,
    priceRange: "25.000đ - 40.000đ",
    priceLevel: "low",
    time: "07:00 - 21:30",
    mustTry: "Cà phê trứng nóng / Cacao trứng / Nước đá me chua ngọt",
    review: "Quán nằm trên gác 2 một căn nhà cổ view nhìn thẳng ra Hồ Gươm. Lớp kem trứng đánh bông mịn như nhung, ngọt béo thơm lừng không một chút mùi tanh kết hợp cùng cà phê Robusta đậm đặc.",
    tags: ["Cafe trứng", "View Hồ Gươm", "Cổ kính", "Giá rẻ"],
    vibe: ["Chill", "Hẹn hò", "Truyền thống"],
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-4",
    name: "Loading T Cafe - Biệt Thự Pháp Cổ",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "8 Chân Cầm, Hàng Trống, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Loading+T+Cafe+8+Chan+Cam+Ha+Noi",
    rating: 4.6,
    reviewCount: 1150,
    priceRange: "45.000đ - 65.000đ",
    priceLevel: "mid",
    time: "08:00 - 18:30",
    mustTry: "Cà phê quế nướng thơm nồng / Trà thảo mộc hoa quả / Bánh chuối",
    review: "Nằm trong căn biệt thự Pháp cổ trăm tuổi với gạch hoa và tường rêu phong. Món cà phê quế đặc trưng thơm nức, không gian cực kỳ lãng mạn, ấm áp và hoài niệm.",
    tags: ["Biệt thự Pháp", "Cafe quế", "Vintage", "Hoàn Kiếm"],
    vibe: ["Hẹn hò", "Chill", "Check-in"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-5",
    name: "Blackbird Coffee - Chân Cầm",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "5 Chân Cầm, Hàng Trống, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Blackbird+Coffee+5+Chan+Cam+Ha+Noi",
    rating: 4.5,
    reviewCount: 1300,
    priceRange: "45.000đ - 70.000đ",
    priceLevel: "mid",
    time: "07:30 - 21:30",
    mustTry: "Eggnog Coffee / Cold Brew Cam sả / Espresso Tonic",
    review: "Quán cà phê tone cam ấm cúng nổi bật giữa phố Chân Cầm. Dòng cà phê Specialty rang xay chuẩn chỉnh, barista chuyên nghiệp và không gian đậm chất indie hiện đại.",
    tags: ["Specialty Coffee", "Tone Cam", "Hiện đại", "Phố Cổ"],
    vibe: ["Hẹn hò", "Chill", "Làm việc"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-6",
    name: "Cafe Lâm - Nguyễn Hữu Huân",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "60 Nguyễn Hữu Huân, Hàng Bạc, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cafe+Lam+60+Nguyen+Huu+Huan+Ha+Noi",
    rating: 4.3,
    reviewCount: 1850,
    priceRange: "25.000đ - 45.000đ",
    priceLevel: "low",
    time: "07:00 - 22:00",
    mustTry: "Cà phê đen phin rang mộc / Nâu đá truyền thống",
    review: "Một trong 'tứ trụ cà phê Hà Nội' (Nhân - Nhĩ - Dĩ - Giảng - Lâm). Nổi tiếng với cà phê rang mộc khét khét đậm đà và bộ sưu tập tranh quý của các danh họa Việt Nam.",
    tags: ["Tứ trụ cafe", "Cafe rang mộc", "Hội họa", "Hoàn Kiếm"],
    vibe: ["Truyền thống", "Chill"],
    image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-7",
    name: "Yên Cafe (Quán Cà Phê Yên Quán Thánh)",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "184 Quán Thánh, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Yen+Cafe+184+Quan+Thanh+Ha+Noi",
    rating: 4.6,
    reviewCount: 3300,
    priceRange: "35.000đ - 55.000đ",
    priceLevel: "low",
    time: "07:30 - 18:00",
    mustTry: "Sapa (Cà phê sữa tươi ngậy) / Katabata / Vàng Nắng",
    review: "Điểm hẹn cà phê quen thuộc của giới trẻ Hà Thành. Món 'Sapa' với sữa béo thanh tao ngọt dịu kết hợp hoàn hảo cùng hạt Arabica, ngồi vỉa hè ngắm phố cực chill.",
    tags: ["Sapa Yên", "Vỉa hè chill", "Ba Đình", "Quán Thánh"],
    vibe: ["Chill", "Hẹn hò", "Làm việc"],
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-8",
    name: "All Day Coffee - Đội Cấn",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "154 Đội Cấn, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=All+Day+Coffee+154+Doi+Can+Ba+Dinh+Ha+Noi",
    rating: 4.5,
    reviewCount: 2900,
    priceRange: "50.000đ - 85.000đ",
    priceLevel: "mid",
    time: "07:00 - 23:00",
    mustTry: "All Day Cold Brew / Trà bưởi hồng / Bánh Croissant nướng bơ",
    review: "Không gian thiết kế phong cách châu Âu sang trọng và ấm cúng. Hạt cà phê được tuyển chọn và rang xay tại chỗ, bánh ngọt tươi ngon nướng mỗi ngày.",
    tags: ["Châu Âu", "Sang trọng", "Làm việc", "Ba Đình"],
    vibe: ["Làm việc", "Hẹn hò", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-9",
    name: "Tranquil Books & Coffee - Quán Thánh",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "18B Nguyễn Biểu, Quán Thánh, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Tranquil+Books+Coffee+Nguyen+Bieu+Ha+Noi",
    rating: 4.6,
    reviewCount: 1850,
    priceRange: "40.000đ - 65.000đ",
    priceLevel: "mid",
    time: "08:00 - 22:30",
    mustTry: "Pourover Ethiopia / Trà Earl Grey / Cà phê kem béo",
    review: "Không gian tĩnh lặng ngập tràn sách và giai điệu Jazz êm dịu. Nơi lý tưởng nhất để đọc sách, làm việc tập trung hoặc trò chuyện thì thầm nhẹ nhàng.",
    tags: ["Yên tĩnh", "Đọc sách", "Làm việc", "Ba Đình"],
    vibe: ["Làm việc", "Chill", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-10",
    name: "Lermalermer Cafe - Ngõ Yên Thế",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "16 Ngõ Yên Thế, Văn Miếu, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Lermalermer+Cafe+Yen+The+Ha+Noi",
    rating: 4.4,
    reviewCount: 480,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "08:00 - 23:00",
    mustTry: "Trà đào dâu tây thảo mộc / Cà phê cốt dừa / Cookie kem",
    review: "Ẩn mình trong con ngõ nhỏ yên ả, quán mang phong cách gác xép mộc mạc với khoảng sân vườn ngập nắng rợp bóng cây xanh mát.",
    tags: ["Ngõ nhỏ", "Sân vườn", "Chill", "Ba Đình"],
    vibe: ["Chill", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-11",
    name: "Kafeville - Specialty Coffee",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "Ngõ 24 Kim Mã / Yên Phụ, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Kafeville+Specialty+Coffee+Ha+Noi",
    rating: 4.5,
    reviewCount: 420,
    priceRange: "45.000đ - 75.000đ",
    priceLevel: "mid",
    time: "08:00 - 18:00",
    mustTry: "Handbrew V60 hạt Geisha / Cold Drip / Flat White",
    review: "Thiên đường cho những người sành cà phê specialty đích thực. Từng mẻ hạt cà phê được lựa chọn kỹ lưỡng và chiết xuất thủ công chuẩn xác từng gram.",
    tags: ["Specialty Coffee", "V60", "Chuyên sâu", "Ba Đình"],
    vibe: ["Chill", "Làm việc"],
    image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-12",
    name: "6 Degrees - Rooftop View Hồ Tây",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "189 Nghi Tàm, Yên Phụ, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=6+Degrees+189+Nghi+Tam+Tay+Ho+Ha+Noi",
    rating: 4.3,
    reviewCount: 2150,
    priceRange: "60.000đ - 120.000đ",
    priceLevel: "high",
    time: "09:00 - 23:00",
    mustTry: "Cocktail hoa quả / Sinh tố nhiệt đới / Cà phê Ý cao cấp",
    review: "Rooftop cafe & lounge nằm trên tầng 8 với tầm nhìn panorama 360 độ ngắm trọn vẹn hoàng hôn Hồ Tây lộng gió. Không gian cực kỳ sang trọng và lãng mạn.",
    tags: ["Rooftop", "View Hồ Tây", "Hoàng hôn", "Tây Hồ"],
    vibe: ["Hẹn hò", "Tụ tập bạn bè", "Check-in"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-13",
    name: "Maison de Tet Decor - Biệt Thự Ven Hồ",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "26 Quảng Bá / Ngõ 1 Từ Hoa, Quảng An, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Maison+de+Tet+Decor+Tay+Ho+Ha+Noi",
    rating: 4.3,
    reviewCount: 1450,
    priceRange: "65.000đ - 120.000đ",
    priceLevel: "high",
    time: "07:30 - 22:00",
    mustTry: "Specialty Espresso / Trà hữu cơ / Bữa sáng Brunch kiểu Âu",
    review: "Ngôi biệt thự Pháp cổ ven Hồ Tây với khoảng sân vườn rợp bóng cây xanh. Cà phê rang mộc tự sản xuất và thực đơn món ăn lành mạnh healthy chuẩn quốc tế.",
    tags: ["Ven Hồ Tây", "Biệt thự Pháp", "Brunch", "Tây Hồ"],
    vibe: ["Hẹn hò", "Gia đình", "Chill"],
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-14",
    name: "Tháng Mười Cafe - Nguyễn Đình Thi",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "115 Nguyễn Đình Thi, Thụy Khuê, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Thang+Muoi+Cafe+115+Nguyen+Dinh+Thi+Ha+Noi",
    rating: 4.4,
    reviewCount: 920,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "07:30 - 23:00",
    mustTry: "Trà hoa cúc mật ong / Cà phê sữa đá / Nước ép tươi",
    review: "Quán cafe mang phong cách vintage cổ điển với hàng ngàn món đồ lưu niệm độc lạ từ khắp nơi. Ban công tầng 3-4 đón gió lộng và ngắm hoàng hôn Hồ Tây cực phẩm.",
    tags: ["View Hồ Tây", "Vintage cổ điển", "Hoàng hôn", "Tây Hồ"],
    vibe: ["Chill", "Hẹn hò", "Check-in"],
    image: "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-15",
    name: "Maison de Éte - Cafe Tone Kem Hàn Quốc",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "Ngõ 4B Đặng Văn Ngữ, Trung Tự, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Maison+de+Ete+Dang+Van+Ngu+Ha+Noi",
    rating: 4.6,
    reviewCount: 580,
    priceRange: "45.000đ - 65.000đ",
    priceLevel: "low",
    time: "09:00 - 21:00",
    mustTry: "Trà đào cam sả thảo mộc / Bánh sừng bò kem tươi / Nước ép nguyên chất",
    review: "Không gian xinh xắn tone gỗ sáng và kem trắng chuẩn style Hàn Quốc, ánh sáng tự nhiên tuyệt đẹp cho các bạn thích chụp ảnh sống ảo. Đồ uống thanh mát, bánh ngọt tươi mỗi ngày.",
    tags: ["Style Hàn Quốc", "Check-in", "Đặng Văn Ngữ", "Đống Đa"],
    vibe: ["Hẹn hò", "Chill", "Check-in"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-16",
    name: "Nhà Trong Ngõ - Đặng Văn Ngữ",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "76 Ngõ 4B Đặng Văn Ngữ, Trung Tự, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Nha+Trong+Ngo+Dang+Van+Ngu+Ha+Noi",
    rating: 4.5,
    reviewCount: 890,
    priceRange: "30.000đ - 50.000đ",
    priceLevel: "low",
    time: "07:30 - 23:00",
    mustTry: "Bạc xỉu ba tầng / Cà phê muối béo ngậy / Trà nhài sen",
    review: "Không gian mộc mạc không điều hòa, ngồi ghế gỗ vỉa hè trong ngõ nhỏ đậm chất Hà Nội xưa. Đồ uống ngon, giá hạt dẻ rất được sinh viên và dân văn phòng yêu thích.",
    tags: ["Ngõ nhỏ", "Bạc xỉu", "Giá rẻ", "Đống Đa"],
    vibe: ["Chill", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1507133750040-3a7f57a05f47?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-17",
    name: "Koh Yam Cafe & Thai Tea - Thái Hà",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "26 Thái Hà, Trung Liệt, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Koh+Yam+26+Thai+Ha+Dong+Da+Ha+Noi",
    rating: 4.4,
    reviewCount: 1250,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "mid",
    time: "09:00 - 22:30",
    mustTry: "Trà sữa Thái đỏ trân châu / Cốt dừa sầu riêng / Kem xôi dừa Thái",
    review: "Thương hiệu trà sữa và đồ uống chuẩn vị đường phố Thái Lan. Vị trà đậm đà béo ngậy kết hợp thạch dừa giòn sần sật, không gian rộng rãi mát lạnh.",
    tags: ["Trà sữa Thái", "Thái Hà", "Tụ tập", "Đống Đa"],
    vibe: ["Tụ tập bạn bè", "Ăn vặt"],
    image: "https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-18",
    name: "Cà Phê Cốt Dừa Cô Hạnh - Duy Tân",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "56 Duy Tân, Dịch Vọng Hậu, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cafe+Cot+Dua+Co+Hanh+56+Duy+Tan+Cau+Giay+Ha+Noi",
    rating: 4.5,
    reviewCount: 980,
    priceRange: "25.000đ - 45.000đ",
    priceLevel: "low",
    time: "07:00 - 22:30",
    mustTry: "Cà phê cốt dừa Hải Phòng đặc sánh / Dừa dầm thạch cốt dừa",
    review: "Đặc sản cà phê cốt dừa Hải Phòng trứ danh với lớp kem cốt dừa xay mịn béo ngậy ngập tràn dừa nạo và thạch giòn, đánh thức mọi giác quan ngày hè.",
    tags: ["Cốt dừa Hải Phòng", "Duy Tân", "Văn phòng", "Cầu Giấy"],
    vibe: ["Ăn nhanh", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1572286258217-215cf8b73f85?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-19",
    name: "Lofita Tea & Coffee - Cầu Giấy",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "2A Hồ Tùng Mậu / 225 Trần Thái Tông, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Lofita+Tea+Coffee+Ho+Tung+Mau+Cau+Giay+Ha+Noi",
    rating: 4.4,
    reviewCount: 850,
    priceRange: "40.000đ - 65.000đ",
    priceLevel: "mid",
    time: "07:30 - 22:30",
    mustTry: "Trà đào hạt chia / Set trà chiều phong cách Hoàng gia / Sinh tố detox",
    review: "Quán cafe rooftop view ngắm trọn ngã tư sầm uất Cầu Giấy. Thiết kế phong cách Paris lãng mạn, menu đồ uống thanh lọc detox tốt cho sức khỏe.",
    tags: ["Rooftop", "Trà hoa quả", "Sống ảo", "Cầu Giấy"],
    vibe: ["Hẹn hò", "Check-in", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-20",
    name: "Twitter Beans Coffee - Hoàng Đạo Thúy",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "Tầng 1 Tòa nhà 17T5 Hoàng Đạo Thúy, Trung Hòa, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Twitter+Beans+Coffee+Hoang+Dao+Thuy+Cau+Giay+Ha+Noi",
    rating: 4.3,
    reviewCount: 1180,
    priceRange: "40.000đ - 70.000đ",
    priceLevel: "mid",
    time: "07:00 - 22:00",
    mustTry: "Freeze Matcha kem tuyết / Caramel Macchiato / Bánh Muffin socola",
    review: "Chuỗi cà phê hiện đại quen thuộc của dân công nghệ và văn phòng khu Trung Hòa - Cầu Giấy. Không gian mở nhiều ổ cắm điện, bàn rộng thích hợp học tập và làm việc.",
    tags: ["Làm việc", "Văn phòng", "Matcha", "Cầu Giấy"],
    vibe: ["Làm việc", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    featured: false
  },

  // ==========================================
  // 🍜 CÁC QUÁN ĂN NỔI TIẾNG HÀ NỘI
  // ==========================================
  {
    id: "place-1",
    name: "Phở Gia Truyền Bát Đàn",
    category: "mon-soi",
    district: "Hoàn Kiếm",
    address: "49 Bát Đàn, Cửa Đông, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Pho+Gia+Truyen+Bat+Dan+49+Bat+Dan+Ha+Noi",
    rating: 4.8,
    reviewCount: 6500,
    priceRange: "55.000đ - 85.000đ",
    priceLevel: "mid",
    time: "06:00 - 10:00 & 18:00 - 20:30",
    mustTry: "Phở Tái Nạm + Quẩy giòn chấm nước dùng",
    review: "Nước dùng trong, ngọt thanh từ xương ống bò ninh kỹ chứ không hề lạm dụng mì chính. Thịt bò tươi xắt mỏng tái mềm, nạm giòn thơm. Điểm trừ là luôn phải xếp hàng tự bưng bê nhưng hương vị hoàn toàn xứng đáng!",
    tags: ["Ăn sáng", "Phố Cổ", "Đặc sản Hà Nội", "Xếp hàng"],
    vibe: ["Truyền thống", "Ăn nhanh", "Gia đình"],
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-2",
    name: "Bún Chả Hương Liên (Bún Chả Obama)",
    category: "mon-soi",
    district: "Hai Bà Trưng",
    address: "24 Lê Văn Hưu, Phan Chu Trinh, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Bun+Cha+Huong+Lien+24+Le+Van+Huu+Ha+Noi",
    rating: 4.6,
    reviewCount: 8200,
    priceRange: "50.000đ - 70.000đ",
    priceLevel: "mid",
    time: "08:00 - 20:30",
    mustTry: "Combo Bún chả đặc biệt + Nem hải sản giòn rụm",
    review: "Chả viên và chả miếng nướng than hoa thơm lừng, thịt tẩm ướp đậm đà vừa miệng. Nước chấm chua ngọt hài hòa, đu đủ xanh giòn sần sật. Nem cua bể vỏ giòn tan, nhân đầy đặn.",
    tags: ["Bún chả", "Nổi tiếng", "Khách du lịch", "Hai Bà Trưng"],
    vibe: ["Truyền thống", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-4",
    name: "Xôi Yến Nguyễn Hữu Huân",
    category: "com-xoi",
    district: "Hoàn Kiếm",
    address: "35B Nguyễn Hữu Huân, Lý Thái Tổ, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Xoi+Yen+35B+Nguyen+Huu+Huan+Ha+Noi",
    rating: 4.5,
    reviewCount: 5400,
    priceRange: "40.000đ - 70.000đ",
    priceLevel: "mid",
    time: "06:00 - 23:00",
    mustTry: "Xôi xéo gà xào nấm + Thịt kho trứng ốp",
    review: "Hạt xôi vàng óng, dẻo mềm thơm mùi nếp cái hoa vàng, đậu xanh bào mịn như tơ, rưới thêm chút mỡ hành thơm ngậy và hành phi giòn tan. Topping thịt kho mềm tan ngập sốt đậm đà.",
    tags: ["Xôi xéo", "Ăn đêm", "Phố Cổ", "Đậm đà"],
    vibe: ["Ăn nhanh", "Gia đình"],
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-5",
    name: "Phở Cuốn Chinh Thắng - Ngũ Xã",
    category: "banh-mi-cuon",
    district: "Ba Đình",
    address: "7 Mạc Đĩnh Chi, Trúc Bạch, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Pho+Cuon+Chinh+Thang+7+Mac+Dinh+Chi+Ha+Noi",
    rating: 4.7,
    reviewCount: 2800,
    priceRange: "60.000đ - 120.000đ",
    priceLevel: "mid",
    time: "09:00 - 22:00",
    mustTry: "Phở cuốn thịt bò + Phở chiên phồng sốt bò cải",
    review: "Bánh phở mềm dẻo cuốn trọn thịt bò xào lăn thơm phức cùng rau sống thanh mát chấm nước mắm chua ngọt. Đặc biệt phở chiên phồng vàng rụm giòn rụm bên ngoài, ngấm đẫm sốt thịt bò cải xào sền sệt cực đã.",
    tags: ["Phở cuốn", "Phở chiên phồng", "Ba Đình", "Hồ Trúc Bạch"],
    vibe: ["Tụ tập bạn bè", "Gia đình"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-6",
    name: "Lẩu Ếch Dũng Béo - Lò Đúc",
    category: "lau-nuong",
    district: "Hai Bà Trưng",
    address: "338 Lò Đúc, Đống Mác, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Lau+Ech+Dung+Beo+338+Lo+Duc+Ha+Noi",
    rating: 4.7,
    reviewCount: 1600,
    priceRange: "150.000đ - 220.000đ / người",
    priceLevel: "high",
    time: "10:30 - 14:00 & 17:00 - 23:30",
    mustTry: "Nồi lẩu ếch măng cay + Ếch xào chua ngọt + Da ếch chiên giòn",
    review: "Thịt ếch tươi rói được xào sơ ngấm đượm sốt tỏi ớt vàng ươm, săn chắc ngọt thịt. Nước lẩu nấu măng cay chua chua cay cay bùng nổ vị giác, nhúng rau muống giòn sần sật ăn giữa ngày se lạnh Hà Nội là chuẩn bài.",
    tags: ["Lẩu ếch", "Măng cay", "Nhậu ngon", "Tụ tập"],
    vibe: ["Tụ tập bạn bè", "Nhậu đêm"],
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-8",
    name: "Bánh Mì 25 - Hàng Cá",
    category: "banh-mi-cuon",
    district: "Hoàn Kiếm",
    address: "25 Hàng Cá, Hàng Đào, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Banh+Mi+25+25+Hang+Ca+Ha+Noi",
    rating: 4.8,
    reviewCount: 11000,
    priceRange: "35.000đ - 50.000đ",
    priceLevel: "low",
    time: "07:00 - 21:00",
    mustTry: "Bánh mì thập cẩm pate bơ thịt nguội + Bánh mì bò phô mai",
    review: "Vỏ bánh mì luôn được nướng nóng giòn tan, pate nhà làm béo thơm mịn màng kết hợp rau dưa nộm thanh mát không hề ngấy. Nhân viên thân thiện, phục vụ nhanh.",
    tags: ["Bánh mì", "Phố Cổ", "Giá rẻ", "Take-away"],
    vibe: ["Ăn nhanh", "Chill"],
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-12",
    name: "Chả Cá Thăng Long - Đường Thành",
    category: "mon-soi",
    district: "Hoàn Kiếm",
    address: "19-21-2D Đường Thành, Cửa Đông, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cha+Ca+Thang+Long+19+Duong+Thanh+Ha+Noi",
    rating: 4.7,
    reviewCount: 3900,
    priceRange: "180.000đ - 250.000đ / người",
    priceLevel: "high",
    time: "10:30 - 21:30",
    mustTry: "Suất Chả cá Lăng xào thì là hành hoa + Mắm tôm đánh sủi bọt",
    review: "Thịt cá lăng lọc xương thái miếng vuông vắn, tẩm nghệ vàng ươm nướng thơm rồi đảo trực tiếp trên chảo dầu cùng hành hoa, thì là. Ăn kèm bún rối, lạc rang và mắm tôm đánh chanh ớt sủi bọt dậy mùi.",
    tags: ["Chả cá Lăng", "Đặc sản Hà Nội", "Sang trọng", "Phố Cổ"],
    vibe: ["Gia đình", "Tiếp khách", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-16",
    name: "Pizza 4P's - Phan Kế Bính",
    category: "do-a-au",
    district: "Ba Đình",
    address: "5 Phan Kế Bính, Cống Vị, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Pizza+4Ps+Phan+Ke+Binh+Ha+Noi",
    rating: 4.9,
    reviewCount: 4200,
    priceRange: "200.000đ - 350.000đ / người",
    priceLevel: "high",
    time: "10:00 - 22:30",
    mustTry: "Pizza 4 Phô mai kèm mật ong + Mì Ý cua sốt kem cà chua",
    review: "Phô mai tươi Burrata tự làm béo ngậy khó cưỡng. Đế pizza mỏng nướng lò củi giòn viền thơm nức. Không gian thiết kế tinh tế, phục vụ chuẩn Nhật Bản chu đáo từng chi tiết.",
    tags: ["Pizza 4P's", "Phô mai Burrata", "Hẹn hò sang xịn", "Đồ Âu"],
    vibe: ["Hẹn hò", "Gia đình", "Tiếp khách"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-19",
    name: "Bít Tết Ba Duy - Vạn Bảo",
    category: "do-a-au",
    district: "Ba Đình",
    address: "105N3, Ngõ 34 Phố Vạn Bảo, Ngọc Hà, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Bit+Tet+Ba+Duy+105N3+Ngo+34+Van+Bao+Ba+Dinh+Ha+Noi",
    rating: 4.8,
    reviewCount: 570,
    priceRange: "80.000đ - 150.000đ / người",
    priceLevel: "mid",
    time: "07:00 - 21:30",
    mustTry: "Bít tết bò chảo gang sốt bơ tỏi / tiêu đen + Bánh mì giòn rụm + Salad dưa chuột",
    review: "Quán bít tết lâu năm rất nổi tiếng ở khu Vạn Bảo. Thịt bò tươi mềm ngọt ngấm sốt đậm đà thơm nức trên chảo gang nóng xèo xèo, ăn kèm pate béo ngậy, trứng ốp la lòng đào và bánh mì nướng giòn tan.",
    tags: ["Bít tết", "Chảo gang", "Vạn Bảo", "Ba Đình", "Ăn no"],
    vibe: ["Gia đình", "Tụ tập bạn bè", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    featured: true
  }
];

const DISTRICTS = [
  "Tất cả quận",
  "Hoàn Kiếm",
  "Ba Đình",
  "Hai Bà Trưng",
  "Đống Đa",
  "Cầu Giấy",
  "Tây Hồ",
  "Thanh Xuân"
];

// Profile tác giả / Curator
const DEFAULT_PROFILE = {
  name: "Hanoi Food & Cafe Guide",
  handle: "@foodie_hanoi",
  bio: "Cẩm nang ẩm thực & cà phê chọn lọc tại Hà Nội. Đạt chuẩn đánh giá >= 4.0★ và hơn 100+ lượt reviews Google Maps! 🥢☕✨",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
  socials: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    tiktok: "https://tiktok.com",
    threads: "https://threads.net"
  },
  stats: {
    placesCount: INITIAL_PLACES.length,
    cities: "Hà Nội",
    verified: true
  }
};
