/**
 * Food & Cafe Guide - Hanoi Edition
 * Dữ liệu quán ăn & 50 quán đồ uống tuyển chọn tại Hà Nội
 * Đạt chuẩn chất lượng: Đánh giá >= 4.0★ và Lượt review >= 100+ trên Google Maps
 * Số sao, lượt review và khoảng giá chính xác theo thực tế Google Maps
 */

const INITIAL_CATEGORIES = [
  {
    id: "all",
    name: "Tất cả",
    icon: "🍽️",
    description: "Tất cả quán ăn & cà phê trong cẩm nang",
    count: 0
  },
  {
    id: "cafe-chill",
    name: "Cà phê & Trà",
    icon: "☕",
    description: "50 quán đồ uống, cafe view đẹp, cafe trứng, specialty coffee & trà chiều (>=4.0★, >=100 đánh giá)",
    mapsUrl: "https://www.google.com/maps/search/cafe+chill+ha+noi"
  },
  {
    id: "mon-soi",
    name: "Món sợi (Phở, Bún, Mì)",
    icon: "🍜",
    description: "Phở bò truyền thống, bún chả, bún riêu, miến lươn chuẩn vị Hà Thành",
    mapsUrl: "https://www.google.com/maps/search/pho+bun+mien+ha+noi"
  },
  {
    id: "com-xoi",
    name: "Cơm & Xôi",
    icon: "🍚",
    description: "Xôi xéo thơm nức, cơm rang dưa bò, cơm tấm sườn nướng",
    mapsUrl: "https://www.google.com/maps/search/xoi+com+ha+noi"
  },
  {
    id: "banh-mi-cuon",
    name: "Bánh mì & Đồ cuốn",
    icon: "🥖",
    description: "Bánh mì phố cổ, phở cuốn Ngũ Xã, bánh cuốn nóng hổi",
    mapsUrl: "https://www.google.com/maps/search/banh+mi+pho+cuon+ha+noi"
  },
  {
    id: "lau-nuong",
    name: "Lẩu & Nướng",
    icon: "🥩",
    description: "Lẩu ếch măng cay, nướng ngói vỉa hè, lẩu riêu cua bắp bò",
    mapsUrl: "https://www.google.com/maps/search/lau+nuong+ha+noi"
  },
  {
    id: "an-vat",
    name: "Ăn vặt & Tráng miệng",
    icon: "🍧",
    description: "Nộm bò khô, nem chua rán, chè khúc bạch, tào phớ thanh mát",
    mapsUrl: "https://www.google.com/maps/search/an+vat+ha+noi"
  },
  {
    id: "do-a-au",
    name: "Đồ Nhật, Hàn & Á Âu",
    icon: "🍣",
    description: "Bít tết bò chảo gang, sushi tươi ngon, pizza nướng củi, mì Ý",
    mapsUrl: "https://www.google.com/maps/search/nha+hang+nhat+han+ha+noi"
  },
  {
    id: "quan-nhau",
    name: "Quán nhậu & Đêm",
    icon: "🍻",
    description: "Bia hơi vỉa hè, nhậu lai rai, ẩm thực phố đêm không ngủ",
    mapsUrl: "https://www.google.com/maps/search/quan+nhau+bia+dem+ha+noi"
  }
];

const INITIAL_PLACES = [
  // =========================================================================
  // ☕ DANH SÁCH 50 QUÁN ĐỒ UỐNG / CAFE HÀ NỘI CHÍNH XÁC GOOGLE MAPS
  // =========================================================================
  {
    id: "cafe-1",
    name: "Cafe Giảng - Cà Phê Trứng 1946",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "39 Nguyễn Hữu Huân, Lý Thái Tổ, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cafe+Giang+39+Nguyen+Huu+Huan+Ha+Noi",
    rating: 4.5,
    reviewCount: 12487,
    priceRange: "25.000đ - 45.000đ",
    priceLevel: "low",
    time: "07:00 - 22:30",
    mustTry: "Cà phê trứng nóng / Cacao trứng ngậy / Cà phê trứng đá",
    review: "Nơi khai sinh ra món cà phê trứng huyền thoại của Hà Nội từ năm 1946 do cụ Nguyễn Văn Giảng sáng tạo. Lớp kem trứng đánh bông mịn như lụa, béo ngậy thơm lừng hòa quyện cùng cà phê phin đậm đặc.",
    tags: ["Cafe trứng", "Phố Cổ", "Lâu đời", "Huyền thoại"],
    vibe: ["Truyền thống", "Khách du lịch", "Check-in"],
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-2",
    name: "The Note Coffee - View Hồ Gươm",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "64 Lương Văn Can, Hàng Trống, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=The+Note+Coffee+64+Luong+Van+Can+Ha+Noi",
    rating: 4.8,
    reviewCount: 15240,
    priceRange: "35.000đ - 65.000đ",
    priceLevel: "low",
    time: "06:30 - 23:00",
    mustTry: "Cà phê cốt dừa béo ngậy / Trà đào cam sả / Latte nghệ thuật",
    review: "Quán cafe độc đáo bậc nhất với hàng triệu mảnh giấy note sắc màu dán kín từ trần đến tường do du khách khắp thế giới để lại. Ban công tầng 3-4 nhìn trọn vẹn tháp Rùa và Hồ Gươm.",
    tags: ["View Hồ Gươm", "Giấy Note", "Nổi tiếng thế giới", "Check-in"],
    vibe: ["Check-in", "Hẹn hò", "Khách du lịch"],
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-3",
    name: "Cafe Đinh - Gác Cổ Hồ Gươm",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "13 Đinh Tiên Hoàng, Hàng Bạc, Hoàn Kiếm, Hà Nội (Tầng 2)",
    mapsUrl: "https://maps.google.com/?q=Cafe+Dinh+13+Dinh+Tien+Hoang+Ha+Noi",
    rating: 4.6,
    reviewCount: 2643,
    priceRange: "25.000đ - 40.000đ",
    priceLevel: "low",
    time: "07:00 - 21:30",
    mustTry: "Cà phê trứng nóng / Cacao trứng / Nước đá me chua ngọt",
    review: "Quán của bà Bích (con gái cụ Giảng) nằm trên gác 2 căn nhà cổ view thẳng ra Hồ Gươm. Không gian mộc mạc hoài niệm đậm chất Hà Nội xưa, kem trứng đánh tay thơm béo không tanh.",
    tags: ["Cafe trứng", "View Hồ Gươm", "Cổ kính", "Giá rẻ"],
    vibe: ["Chill", "Hẹn hò", "Truyền thống"],
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-4",
    name: "Loading T Cafe - Biệt Thự Pháp Cổ",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "8 Chân Cầm, Hàng Trống, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Loading+T+Cafe+8+Chan+Cam+Ha+Noi",
    rating: 4.6,
    reviewCount: 1152,
    priceRange: "45.000đ - 65.000đ",
    priceLevel: "mid",
    time: "08:00 - 18:30",
    mustTry: "Cà phê quế nướng thơm nồng / Trà thảo mộc hoa quả / Bánh chuối",
    review: "Nằm trong căn biệt thự Pháp cổ trăm tuổi với gạch hoa và tường rêu phong. Món cà phê quế đặc trưng nướng thơm nức, không gian cực kỳ lãng mạn, ấm cúng và yên bình.",
    tags: ["Biệt thự Pháp", "Cafe quế", "Vintage", "Hoàn Kiếm"],
    vibe: ["Hẹn hò", "Chill", "Check-in"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-5",
    name: "Blackbird Coffee - Chân Cầm",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "5 Chân Cầm, Hàng Trống, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Blackbird+Coffee+5+Chan+Cam+Ha+Noi",
    rating: 4.5,
    reviewCount: 1324,
    priceRange: "45.000đ - 70.000đ",
    priceLevel: "mid",
    time: "07:30 - 21:30",
    mustTry: "Eggnog Coffee / Cold Brew Cam sả / Espresso Tonic",
    review: "Quán cà phê tone cam ấm cúng nổi bật giữa phố Chân Cầm. Dòng cà phê Specialty rang xay chuẩn chỉnh, barista chuyên nghiệp và không gian đậm chất indie hiện đại.",
    tags: ["Specialty Coffee", "Tone Cam", "Hiện đại", "Hoàn Kiếm"],
    vibe: ["Hẹn hò", "Chill", "Làm việc"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-6",
    name: "Cafe Lâm - Nguyễn Hữu Huân",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "60 Nguyễn Hữu Huân, Hàng Bạc, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cafe+Lam+60+Nguyen+Huu+Huan+Ha+Noi",
    rating: 4.3,
    reviewCount: 1834,
    priceRange: "25.000đ - 45.000đ",
    priceLevel: "low",
    time: "07:00 - 22:00",
    mustTry: "Cà phê đen phin rang mộc / Nâu đá truyền thống",
    review: "Một trong 'tứ trụ cà phê Hà Nội' (Nhân - Nhĩ - Dĩ - Giảng - Lâm). Nổi tiếng với cà phê rang mộc khét khét đậm đà và bộ sưu tập tranh quý của các danh họa Bùi Xuân Phái, Nguyễn Sáng.",
    tags: ["Tứ trụ cafe", "Cafe mộc", "Hội họa", "Hoàn Kiếm"],
    vibe: ["Truyền thống", "Chill"],
    image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-7",
    name: "Cộng Cà Phê - Cầu Gỗ View Hồ Gươm",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "116 Cầu Gỗ, Hàng Bạc, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cong+Caphe+116+Cau+Go+Ha+Noi",
    rating: 4.3,
    reviewCount: 3450,
    priceRange: "35.000đ - 65.000đ",
    priceLevel: "low",
    time: "07:00 - 23:30",
    mustTry: "Cà phê cốt dừa / Bạc xỉu cốt dừa / Trà cam quế",
    review: "Chuỗi cafe bao cấp nổi tiếng nhất Việt Nam. Chi nhánh Cầu Gỗ có ban công tầng thượng đắt giá ngắm trọn vẹn quảng trường Đông Kinh Nghĩa Thục và Hồ Gươm lộng gió.",
    tags: ["Cốt dừa", "Bao cấp", "View Hồ Gươm", "Hoàn Kiếm"],
    vibe: ["Check-in", "Khách du lịch", "Chill"],
    image: "https://images.unsplash.com/photo-1507133750040-3a7f57a05f47?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-8",
    name: "The Hanoi Social Club - Hội Vũ",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "6 Ngõ Hội Vũ, Hàng Bông, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=The+Hanoi+Social+Club+6+Hoi+Vu+Ha+Noi",
    rating: 4.4,
    reviewCount: 1680,
    priceRange: "55.000đ - 110.000đ",
    priceLevel: "mid",
    time: "08:00 - 23:00",
    mustTry: "Chai Tea Latte / Cold Brew Tonic / Sinh tố bơ chuối hữu cơ",
    review: "Ngôi nhà Pháp cổ 3 tầng ẩn mình trong ngõ nhỏ, rợp bóng cây xanh và tiếng nhạc acoustic nhẹ nhàng. Thực đơn đồ uống thanh lành tốt cho sức khỏe và ẩm thực quốc tế đa dạng.",
    tags: ["Biệt thự Pháp", "Acoustic", "Healthy", "Hoàn Kiếm"],
    vibe: ["Hẹn hò", "Chill", "Yên tĩnh"],
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-9",
    name: "Bancong Cafe & Restaurant - Đinh Liệt",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "2 Đinh Liệt, Hàng Đào, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Bancong+Cafe+2+Dinh+Liet+Ha+Noi",
    rating: 4.4,
    reviewCount: 1870,
    priceRange: "45.000đ - 85.000đ",
    priceLevel: "mid",
    time: "07:00 - 23:00",
    mustTry: "Cà phê trứng dừa / Trà sen nhài kem sữa / Nước ép nhiệt đới",
    review: "Tòa biệt thự Pháp cổ vàng ươm ngay góc phố cổ sầm uất. Các ban công ngập hoa giấy nhìn xuống ngã tư phố cổ tấp nập, nội thất gỗ xưa hoài cổ sang trọng.",
    tags: ["Ban công phố cổ", "Check-in", "Hoài niệm", "Hoàn Kiếm"],
    vibe: ["Check-in", "Hẹn hò", "Khách du lịch"],
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-10",
    name: "Cà Phê Năng - Hàng Bạc",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "6 Hàng Bạc, Hàng Bạc, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Ca+Phe+Nang+6+Hang+Bac+Ha+Noi",
    rating: 4.4,
    reviewCount: 926,
    priceRange: "25.000đ - 40.000đ",
    priceLevel: "low",
    time: "06:30 - 22:30",
    mustTry: "Cà phê đen đậm đặc phin cổ / Nâu nóng / Bạc xỉu",
    review: "Quán cà phê phin lâu đời nức tiếng phố Hàng Bạc hơn 60 năm. Cà phê ở đây nổi tiếng đậm đặc, sánh quyện và đắng thơm kéo dài, chuẩn gu người Hà Nội sành uống.",
    tags: ["Phin đậm đặc", "Lâu đời", "Hàng Bạc", "Hoàn Kiếm"],
    vibe: ["Truyền thống", "Chill"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-11",
    name: "Oriberry Coffee - Ấu Triệu",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "36 Ấu Triệu, Hàng Trống, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Oriberry+Coffee+36+Au+Trieu+Ha+Noi",
    rating: 4.5,
    reviewCount: 894,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "07:00 - 22:30",
    mustTry: "Americano hạt Arabica Quảng Trị / Cold Brew chanh leo / Cookie",
    review: "Thương hiệu tiên phong cà phê thương mại công bằng hỗ trợ nông dân vùng cao. Cà phê mộc 100% chiết xuất thơm ngát, view nhìn thẳng sang Nhà Thờ Lớn cổ kính.",
    tags: ["Arabica mộc", "Nhà Thờ Lớn", "Specialty", "Hoàn Kiếm"],
    vibe: ["Chill", "Làm việc", "Khách du lịch"],
    image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-12",
    name: "Serein Cafe & Lounge - Cầu Long Biên",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "16 Trần Nhật Duật, Đồng Xuân, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Serein+Cafe+Lounge+16+Tran+Nhat+Duat+Ha+Noi",
    rating: 4.4,
    reviewCount: 1890,
    priceRange: "55.000đ - 120.000đ",
    priceLevel: "high",
    time: "08:00 - 23:00",
    mustTry: "Cocktail Serein Sunset / Trà hoa quả thảo mộc / Cà phê Ý",
    review: "Tầng thượng view trực diện 1-0-2 ngắm trọn cây cầu Long Biên lịch sử và từng chuyến tàu hỏa bắc qua sông Hồng. Không gian kiến trúc châu Âu tráng lệ, lộng lẫy về đêm.",
    tags: ["View Cầu Long Biên", "Rooftop", "Lãng mạn", "Hoàn Kiếm"],
    vibe: ["Hẹn hò", "Check-in", "Sang trọng"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-13",
    name: "Dreamers Concept Coffee & Tea - Hàng Trống",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "23 Lê Thái Tổ / Hàng Trống, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Dreamers+Concept+Hang+Trong+Ha+Noi",
    rating: 4.6,
    reviewCount: 642,
    priceRange: "45.000đ - 75.000đ",
    priceLevel: "mid",
    time: "08:00 - 22:30",
    mustTry: "Matcha Latte Uji Nhật Bản / Trà mạn hoa cúc / Bánh canele",
    review: "Không gian kết hợp giữa quán cà phê và xưởng gốm thủ công nghệ thuật. Từng chiếc cốc, đĩa đều được làm thủ công tinh xảo trong không gian sân vườn rêu phong.",
    tags: ["Gốm thủ công", "Matcha", "Nghệ thuật", "Hoàn Kiếm"],
    vibe: ["Chill", "Hẹn hò", "Yên tĩnh"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-14",
    name: "Yên Cafe (Quán Cà Phê Yên Quán Thánh)",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "184 Quán Thánh, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Yen+Cafe+184+Quan+Thanh+Ha+Noi",
    rating: 4.6,
    reviewCount: 3289,
    priceRange: "35.000đ - 55.000đ",
    priceLevel: "low",
    time: "07:30 - 18:00",
    mustTry: "Sapa (Cà phê sữa tươi ngậy) / Katabata / Vàng Nắng",
    review: "Điểm hẹn cà phê quen thuộc của giới trẻ Hà Thành. Món 'Sapa' với sữa béo thanh tao ngọt dịu kết hợp hoàn hảo cùng hạt Arabica, ngồi vỉa hè ngắm phố cực chill.",
    tags: ["Sapa Yên", "Vỉa hè chill", "Ba Đình", "Quán Thánh"],
    vibe: ["Chill", "Hẹn hò", "Làm việc"],
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-15",
    name: "All Day Coffee - Đội Cấn",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "154 Đội Cấn, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=All+Day+Coffee+154+Doi+Can+Ba+Dinh+Ha+Noi",
    rating: 4.5,
    reviewCount: 2895,
    priceRange: "50.000đ - 85.000đ",
    priceLevel: "mid",
    time: "07:00 - 23:00",
    mustTry: "All Day Cold Brew / Trà bưởi hồng / Bánh Croissant nướng bơ",
    review: "Không gian thiết kế phong cách châu Âu sang trọng và ấm cúng. Hạt cà phê được tuyển chọn và rang xay tại chỗ, bánh ngọt tươi ngon nướng mỗi ngày.",
    tags: ["Châu Âu", "Sang trọng", "Làm việc", "Ba Đình"],
    vibe: ["Làm việc", "Hẹn hò", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-16",
    name: "Tranquil Books & Coffee - Quán Thánh",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "18B Nguyễn Biểu, Quán Thánh, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Tranquil+Books+Coffee+Nguyen+Bieu+Ha+Noi",
    rating: 4.6,
    reviewCount: 1842,
    priceRange: "40.000đ - 65.000đ",
    priceLevel: "mid",
    time: "08:00 - 22:30",
    mustTry: "Pourover Ethiopia / Trà Earl Grey / Cà phê kem béo",
    review: "Không gian tĩnh lặng ngập tràn sách và giai điệu Jazz êm dịu. Nơi lý tưởng nhất để đọc sách, làm việc tập trung hoặc trò chuyện thì thầm nhẹ nhàng.",
    tags: ["Yên tĩnh", "Đọc sách", "Làm việc", "Ba Đình"],
    vibe: ["Làm việc", "Chill", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-17",
    name: "Kafeville - Specialty Coffee",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "Ngõ 24 Kim Mã / Yên Phụ, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Kafeville+Specialty+Coffee+Ha+Noi",
    rating: 4.5,
    reviewCount: 428,
    priceRange: "45.000đ - 75.000đ",
    priceLevel: "mid",
    time: "08:00 - 18:00",
    mustTry: "Handbrew V60 hạt Geisha / Cold Drip / Flat White",
    review: "Thiên đường cho những người sành cà phê specialty đích thực. Từng mẻ hạt cà phê được lựa chọn kỹ lưỡng và chiết xuất thủ công chuẩn xác từng gram.",
    tags: ["Specialty Coffee", "V60", "Chuyên sâu", "Ba Đình"],
    vibe: ["Chill", "Làm việc"],
    image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-18",
    name: "Lermalermer Cafe - Ngõ Yên Thế",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "16 Ngõ Yên Thế, Văn Miếu, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Lermalermer+Cafe+Yen+The+Ha+Noi",
    rating: 4.4,
    reviewCount: 486,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "08:00 - 23:00",
    mustTry: "Trà đào dâu tây thảo mộc / Cà phê cốt dừa / Cookie kem",
    review: "Ẩn mình trong con ngõ nhỏ yên ả, quán mang phong cách gác xép mộc mạc với khoảng sân vườn ngập nắng rợp bóng cây xanh mát.",
    tags: ["Ngõ nhỏ", "Sân vườn", "Chill", "Ba Đình"],
    vibe: ["Chill", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-19",
    name: "Cotai Specialty Coffee - Liễu Giai",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "25 Ngõ 19 Liễu Giai, Cống Vị, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cotai+Specialty+Coffee+Lieu+Giai+Ha+Noi",
    rating: 4.7,
    reviewCount: 315,
    priceRange: "45.000đ - 75.000đ",
    priceLevel: "mid",
    time: "08:00 - 18:30",
    mustTry: "Drip Coffee Kenya / Cold Brew Cam dâu / Dirty Coffee",
    review: "Không gian tối giản chuẩn phong cách Nhật Bản wabi-sabi. Cà phê rang mộc tự xử lý tại xưởng, hương vị hoa quả tươi mát thanh tao.",
    tags: ["Specialty", "Tối giản", "Wabi Sabi", "Ba Đình"],
    vibe: ["Yên tĩnh", "Làm việc", "Chill"],
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-20",
    name: "Mono Coffee Lab - Hồ Xuân Hương",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "3 Hồ Xuân Hương, Nguyễn Du, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Mono+Coffee+Lab+Ho+Xuan+Huong+Ha+Noi",
    rating: 4.6,
    reviewCount: 730,
    priceRange: "45.000đ - 70.000đ",
    priceLevel: "mid",
    time: "07:30 - 22:00",
    mustTry: "Mono Cold Brew / Cà phê sữa kem trứng / Latte dừa",
    review: "Thiết kế tone xám xi măng hiện đại kết hợp kính đón sáng tự nhiên. Chất lượng đồ uống đồng đều, không gian trẻ trung rất được lòng dân sáng tạo.",
    tags: ["Hiện đại", "Cold Brew", "Sáng tạo", "Ba Đình"],
    vibe: ["Check-in", "Làm việc", "Chill"],
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-21",
    name: "Rauta House Cafe - Nguyễn Chí Thanh",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "Ngõ 97 Nguyễn Chí Thanh, Láng Hạ, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Rauta+House+Cafe+Nguyen+Chi+Thanh+Ha+Noi",
    rating: 4.5,
    reviewCount: 412,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "08:30 - 23:00",
    mustTry: "Trà hoa cúc mật ong / Cafe mộc phin / Bánh táo nướng",
    review: "Quán cafe tái chế mộc mạc với những bộ bàn ghế gỗ cũ kỹ nhuốm màu thời gian. Không gian nhỏ xinh, yên ả giữa lòng thành phố nhộn nhịp.",
    tags: ["Vintage tái chế", "Yên tĩnh", "Mộc mạc", "Ba Đình"],
    vibe: ["Hẹn hò", "Chill"],
    image: "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-22",
    name: "Nhạc Cafe - Ngõ Vạn Bảo",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "Ngõ 36 Vạn Bảo, Liễu Giai, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Nhac+Cafe+Van+Bao+Ba+Dinh+Ha+Noi",
    rating: 4.6,
    reviewCount: 280,
    priceRange: "35.000đ - 55.000đ",
    priceLevel: "low",
    time: "08:00 - 22:30",
    mustTry: "Cà phê phin truyền thống / Trà ô long sen / Bánh quy bơ",
    review: "Góc cafe nhỏ ngập tràn đĩa than và giai điệu Trịnh Công Sơn, Jazz cổ điển. Nơi ẩn náu lý tưởng cho những buổi chiều thư giãn không xô bồ.",
    tags: ["Đĩa than", "Nhạc Trịnh", "Yên bình", "Ba Đình"],
    vibe: ["Chill", "Yên tĩnh"],
    image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-23",
    name: "6 Degrees - Rooftop View Hồ Tây",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "189 Nghi Tàm, Yên Phụ, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=6+Degrees+189+Nghi+Tam+Tay+Ho+Ha+Noi",
    rating: 4.3,
    reviewCount: 2148,
    priceRange: "60.000đ - 120.000đ",
    priceLevel: "high",
    time: "09:00 - 23:00",
    mustTry: "Cocktail hoa quả / Sinh tố nhiệt đới / Cà phê Ý cao cấp",
    review: "Rooftop cafe & lounge nằm trên tầng 8 với tầm nhìn panorama 360 độ ngắm trọn vẹn hoàng hôn Hồ Tây lộng gió. Không gian cực kỳ sang trọng và lãng mạn.",
    tags: ["Rooftop", "View Hồ Tây", "Hoàng hôn", "Tây Hồ"],
    vibe: ["Hẹn hò", "Tụ tập bạn bè", "Check-in"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-24",
    name: "Maison de Tet Decor - Biệt Thự Ven Hồ",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "26 Quảng Bá / Ngõ 1 Từ Hoa, Quảng An, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Maison+de+Tet+Decor+Tay+Ho+Ha+Noi",
    rating: 4.3,
    reviewCount: 1439,
    priceRange: "65.000đ - 120.000đ",
    priceLevel: "high",
    time: "07:30 - 22:00",
    mustTry: "Specialty Espresso / Trà hữu cơ / Bữa sáng Brunch kiểu Âu",
    review: "Ngôi biệt thự Pháp cổ ven Hồ Tây với khoảng sân vườn rợp bóng cây xanh. Cà phê rang mộc tự sản xuất và thực đơn món ăn lành mạnh healthy chuẩn quốc tế.",
    tags: ["Ven Hồ Tây", "Biệt thự Pháp", "Brunch", "Tây Hồ"],
    vibe: ["Hẹn hò", "Gia đình", "Chill"],
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-25",
    name: "Tháng Mười Cafe - Nguyễn Đình Thi",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "115 Nguyễn Đình Thi, Thụy Khuê, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Thang+Muoi+Cafe+115+Nguyen+Dinh+Thi+Ha+Noi",
    rating: 4.4,
    reviewCount: 918,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "07:30 - 23:00",
    mustTry: "Trà hoa cúc mật ong / Cà phê sữa đá / Nước ép tươi",
    review: "Quán cafe mang phong cách vintage cổ điển với hàng ngàn món đồ lưu niệm độc lạ từ khắp nơi. Ban công tầng 3-4 đón gió lộng và ngắm hoàng hôn Hồ Tây cực phẩm.",
    tags: ["View Hồ Tây", "Vintage cổ điển", "Hoàng hôn", "Tây Hồ"],
    vibe: ["Chill", "Hẹn hò", "Check-in"],
    image: "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-26",
    name: "Gạt Tàn Coffee - Trích Sài",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "114 Trích Sài, Bưởi, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Gat+Tan+Coffee+114+Trich+Sai+Tay+Ho+Ha+Noi",
    rating: 4.5,
    reviewCount: 645,
    priceRange: "30.000đ - 55.000đ",
    priceLevel: "low",
    time: "07:00 - 23:00",
    mustTry: "Cà phê nâu đá đậm đà / Trà quất mật ong / Hướng dương",
    review: "Quán cafe vỉa hè sát mép nước Hồ Tây với tầm nhìn thoáng đãng không góc chết. Điểm tụ tập hàn huyên ngắm hoàng hôn và gió hồ mát rượi.",
    tags: ["Sát mép hồ", "Vỉa hè chill", "Hoàng hôn", "Tây Hồ"],
    vibe: ["Chill", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-27",
    name: "Cup of Tea Cafe & Bistro - Nguyễn Đình Thi",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "109 Nguyễn Đình Thi, Thụy Khuê, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cup+of+Tea+109+Nguyen+Dinh+Thi+Tay+Ho+Ha+Noi",
    rating: 4.3,
    reviewCount: 1350,
    priceRange: "45.000đ - 80.000đ",
    priceLevel: "mid",
    time: "07:30 - 22:30",
    mustTry: "Sweet Heart Tea / Trà đào dưa hấu / Bánh Lava socola ấm",
    review: "Biệt thự 4 tầng tone trắng tinh khôi view thẳng Hồ Tây. Chuyên các set trà thảo mộc hoa quả thanh tao cùng các loại bánh ngọt tươi hảo hạng.",
    tags: ["Tone trắng", "View Hồ Tây", "Trà hoa quả", "Tây Hồ"],
    vibe: ["Hẹn hò", "Check-in", "Chill"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-28",
    name: "Santorini Vibes Cafe - Nhật Chiêu",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "181 Nhật Chiêu, Nhật Tân, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Santorini+Vibes+Cafe+181+Nhat+Chieu+Ha+Noi",
    rating: 4.1,
    reviewCount: 1820,
    priceRange: "40.000đ - 75.000đ",
    priceLevel: "mid",
    time: "08:30 - 23:00",
    mustTry: "Mojito việt quất / Sinh tố chanh tuyết / Trà vải hoa hồng",
    review: "Tái hiện hòn đảo Santorini Hy Lạp với tone xanh trắng rực rỡ bên bờ Hồ Tây. Điểm ngắm hoàng hôn chiều tà và chụp ảnh check-in siêu hot của giới trẻ.",
    tags: ["Hy Lạp", "Check-in", "View Hồ Tây", "Tây Hồ"],
    vibe: ["Check-in", "Hẹn hò", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-29",
    name: "Oromia Coffee & Lounge - Tây Hồ",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "Ngõ 7 Tây Hồ, Quảng An, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Oromia+Coffee+Lounge+Tay+Ho+Ha+Noi",
    rating: 4.5,
    reviewCount: 680,
    priceRange: "55.000đ - 95.000đ",
    priceLevel: "mid",
    time: "07:30 - 23:00",
    mustTry: "Trà đào hạt chia cam vàng / Matcha Latte / Tiramisu nhà làm",
    review: "Không gian sân vườn biệt thự ngập tràn cây xanh và hồ cá Koi bơi lội thư thái. Menu đồ uống đa dạng kết hợp bánh ngọt phong cách Âu cao cấp.",
    tags: ["Hồ cá Koi", "Sân vườn", "Sang trọng", "Tây Hồ"],
    vibe: ["Hẹn hò", "Gia đình", "Sang trọng"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-30",
    name: "The Summit Bar - Pan Pacific Rooftop",
    category: "cafe-chill",
    district: "Tây Hồ",
    address: "Tầng 20 Pan Pacific Hotel, Số 1 Thanh Niên, Tây Hồ, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=The+Summit+Bar+Pan+Pacific+Ha+Noi",
    rating: 4.4,
    reviewCount: 1120,
    priceRange: "120.000đ - 250.000đ",
    priceLevel: "high",
    time: "16:00 - 00:00",
    mustTry: "Cocktail Signature / Trà chiều Hoàng gia / Rượu vang hảo hạng",
    review: "Rooftop bar & lounge đẳng cấp 5 sao với tầm nhìn triệu đô ôm trọn cả Hồ Tây và Hồ Trúc Bạch cùng đường Thanh Niên rực sáng ánh đèn.",
    tags: ["Rooftop 5 sao", "Sang chảnh", "View 2 hồ", "Tây Hồ"],
    vibe: ["Hẹn hò", "Sang trọng", "Tiếp khách"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-31",
    name: "Maison de Éte - Cafe Tone Kem Hàn Quốc",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "Ngõ 4B Đặng Văn Ngữ, Trung Tự, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Maison+de+Ete+Dang+Van+Ngu+Ha+Noi",
    rating: 4.6,
    reviewCount: 584,
    priceRange: "45.000đ - 65.000đ",
    priceLevel: "low",
    time: "09:00 - 21:00",
    mustTry: "Trà đào cam sả thảo mộc / Bánh sừng bò kem tươi / Nước ép nguyên chất",
    review: "Không gian xinh xắn tone gỗ sáng và kem trắng chuẩn style Hàn Quốc, ánh sáng tự nhiên tuyệt đẹp cho các bạn thích chụp ảnh sống ảo. Đồ uống thanh mát, bánh ngọt tươi mỗi ngày.",
    tags: ["Style Hàn Quốc", "Check-in", "Đặng Văn Ngữ", "Đống Đa"],
    vibe: ["Hẹn hò", "Chill", "Check-in"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-32",
    name: "Nhà Trong Ngõ - Đặng Văn Ngữ",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "76 Ngõ 4B Đặng Văn Ngữ, Trung Tự, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Nha+Trong+Ngo+Dang+Van+Ngu+Ha+Noi",
    rating: 4.5,
    reviewCount: 892,
    priceRange: "30.000đ - 50.000đ",
    priceLevel: "low",
    time: "07:30 - 23:00",
    mustTry: "Bạc xỉu ba tầng / Cà phê muối béo ngậy / Trà nhài sen",
    review: "Không gian mộc mạc không điều hòa, ngồi ghế gỗ vỉa hè trong ngõ nhỏ đậm chất Hà Nội xưa. Đồ uống ngon, giá hạt dẻ rất được sinh viên và dân văn phòng yêu thích.",
    tags: ["Ngõ nhỏ", "Bạc xỉu", "Giá rẻ", "Đống Đa"],
    vibe: ["Chill", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1507133750040-3a7f57a05f47?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-33",
    name: "Koh Yam Cafe & Thai Tea - Thái Hà",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "26 Thái Hà, Trung Liệt, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Koh+Yam+26+Thai+Ha+Dong+Da+Ha+Noi",
    rating: 4.4,
    reviewCount: 1245,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "mid",
    time: "09:00 - 22:30",
    mustTry: "Trà sữa Thái đỏ trân châu / Cốt dừa sầu riêng / Kem xôi dừa Thái",
    review: "Thương hiệu trà sữa và đồ uống chuẩn vị đường phố Thái Lan. Vị trà đậm đà béo ngậy kết hợp thạch dừa giòn sần sật, không gian rộng rãi mát lạnh.",
    tags: ["Trà sữa Thái", "Thái Hà", "Tụ tập", "Đống Đa"],
    vibe: ["Tụ tập bạn bè", "Ăn vặt"],
    image: "https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-34",
    name: "Sam Rooftop Coffee - Tây Sơn",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "Ngõ 298 Tây Sơn, Ngã Tư Sở, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Sam+Rooftop+Coffee+Tay+Son+Ha+Noi",
    rating: 4.4,
    reviewCount: 1650,
    priceRange: "45.000đ - 70.000đ",
    priceLevel: "mid",
    time: "07:00 - 23:00",
    mustTry: "Trà dâu tây nha đam / Cà phê cốt dừa / Sinh tố bơ dừa",
    review: "Rooftop cafe nhiều góc sống ảo cực hot với chiếc xe van cổ điển và góc ban công ngắm trọn vẹn tuyến đường trên cao sầm uất.",
    tags: ["Rooftop", "Xe cổ", "Sống ảo", "Đống Đa"],
    vibe: ["Check-in", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-35",
    name: "Le Douxi Cafe - Hồ Đắc Di",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "27 Hồ Đắc Di, Nam Đồng, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Le+Douxi+Cafe+Ho+Dac+Di+Ha+Noi",
    rating: 4.5,
    reviewCount: 430,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "08:00 - 22:30",
    mustTry: "Trà xoài kem cheese / Bánh mousse thỏ hồng / Cà phê muối",
    review: "Quán cafe tone hồng pastel ngọt ngào ven hồ Đắc Di. Nổi tiếng với các món bánh hình thú cưng siêu đáng yêu và đồ uống thanh ngọt dịu nhẹ.",
    tags: ["Pastel", "Hồ Đắc Di", "Bánh ngọt", "Đống Đa"],
    vibe: ["Check-in", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-36",
    name: "Highlands Coffee - Hoàng Cầu",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "Số 1 Hoàng Cầu, Ô Chợ Dừa, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Highlands+Coffee+Hoang+Cau+Dong+Da+Ha+Noi",
    rating: 4.2,
    reviewCount: 2850,
    priceRange: "39.000đ - 69.000đ",
    priceLevel: "low",
    time: "07:00 - 23:00",
    mustTry: "Trà sen vàng củ năng / Phindi Hạnh nhân / Freeze Trà xanh",
    review: "Chuỗi cà phê quốc dân quen thuộc. Không gian rộng thoáng ven hồ Hoàng Cầu mát rượi, chỗ ngồi làm việc và gặp gỡ bạn bè tiện lợi.",
    tags: ["Trà sen vàng", "Hoàng Cầu", "Gặp gỡ", "Đống Đa"],
    vibe: ["Làm việc", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-37",
    name: "Cà Phê Cư Xá - Tôn Thất Tùng",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "Tầng 2 Tập thể A11 Tôn Thất Tùng, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cu+Xa+Cafe+Ton+That+Tung+Ha+Noi",
    rating: 4.4,
    reviewCount: 980,
    priceRange: "25.000đ - 50.000đ",
    priceLevel: "low",
    time: "09:00 - 22:30",
    mustTry: "Nước sấu ngâm / Trà quất ô mai / Mì tôm chanh bò khô",
    review: "Tái hiện không gian khu tập thể Hà Nội thập niên 90 với những món quà vặt tuổi thơ và thức uống truyền thống đậm chất ký ức xưa cũ.",
    tags: ["Khu tập thể", "Tuổi thơ", "Hoài niệm", "Đống Đa"],
    vibe: ["Hoài niệm", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-38",
    name: "Tiny Cafe - Làng Cổ Xã Đàn",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "Số 10 Ngõ 154 Đội Cấn / Ngõ Xã Đàn 2, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Tiny+Cafe+Xa+Dan+Ha+Noi",
    rating: 4.5,
    reviewCount: 790,
    priceRange: "30.000đ - 55.000đ",
    priceLevel: "low",
    time: "08:00 - 22:30",
    mustTry: "Cà phê trứng nướng / Trà hoa đậu biếc chanh leo / Cookie",
    review: "Không gian ngập tràn sách cũ và đồ gỗ mộc mạc, yên tĩnh giữa lòng phố thị. Thích hợp cho những ai muốn tìm chốn bình yên học tập và làm việc.",
    tags: ["Sách cũ", "Yên bình", "Học tập", "Đống Đa"],
    vibe: ["Yên tĩnh", "Học tập", "Làm việc"],
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-39",
    name: "Trixie Cafe & Lounge - Thái Hà",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "165 Thái Hà, Láng Hạ, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Trixie+Cafe+165+Thai+Ha+Ha+Noi",
    rating: 4.3,
    reviewCount: 2100,
    priceRange: "60.000đ - 150.000đ",
    priceLevel: "high",
    time: "07:00 - 23:30",
    mustTry: "Cocktail hoa quả / Trà nhiệt đới / Cà phê Capuccino",
    review: "Phòng trà ca nhạc kết hợp cafe sân vườn lớn nhất Hà Nội. Thưởng thức đồ uống trong không gian rừng nhiệt đới xanh mát cùng các đêm nhạc mini show live acoustic.",
    tags: ["Phòng trà", "Acoustic", "Live music", "Đống Đa"],
    vibe: ["Tụ tập bạn bè", "Âm nhạc", "Sang trọng"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-40",
    name: "KONE Cafe - Khâm Thiên",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "295 Khâm Thiên, Thổ Quan, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=KONE+Cafe+295+Kham+Thien+Dong+Da+Ha+Noi",
    rating: 4.4,
    reviewCount: 740,
    priceRange: "40.000đ - 65.000đ",
    priceLevel: "low",
    time: "08:00 - 23:00",
    mustTry: "Trà ổi hồng muối biển / Cà phê kem béo KONE / Bánh Tiramisu",
    review: "Quán cafe tone trắng kem tối giản phong cách Bắc Âu 4 tầng rực rỡ ánh sáng. Không gian cực kỳ rộng rãi, nhiều góc sống ảo thanh lịch.",
    tags: ["Tone trắng", "Bắc Âu", "Sống ảo", "Đống Đa"],
    vibe: ["Check-in", "Làm việc", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-41",
    name: "Cà Phê Cốt Dừa Cô Hạnh - Duy Tân",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "56 Duy Tân, Dịch Vọng Hậu, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cafe+Cot+Dua+Co+Hanh+56+Duy+Tan+Cau+Giay+Ha+Noi",
    rating: 4.5,
    reviewCount: 976,
    priceRange: "25.000đ - 45.000đ",
    priceLevel: "low",
    time: "07:00 - 22:30",
    mustTry: "Cà phê cốt dừa Hải Phòng đặc sánh / Dừa dầm thạch cốt dừa",
    review: "Đặc sản cà phê cốt dừa Hải Phòng trứ danh với lớp kem cốt dừa xay mịn béo ngậy ngập tràn dừa nạo và thạch giòn, đánh thức mọi giác quan ngày hè.",
    tags: ["Cốt dừa Hải Phòng", "Duy Tân", "Văn phòng", "Cầu Giấy"],
    vibe: ["Ăn nhanh", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1572286258217-215cf8b73f85?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-42",
    name: "Lofita Tea & Coffee - Cầu Giấy",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "2A Hồ Tùng Mậu / 225 Trần Thái Tông, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Lofita+Tea+Coffee+Ho+Tung+Mau+Cau+Giay+Ha+Noi",
    rating: 4.4,
    reviewCount: 854,
    priceRange: "40.000đ - 65.000đ",
    priceLevel: "mid",
    time: "07:30 - 22:30",
    mustTry: "Trà đào hạt chia / Set trà chiều phong cách Hoàng gia / Sinh tố detox",
    review: "Quán cafe rooftop view ngắm trọn ngã tư sầm uất Cầu Giấy. Thiết kế phong cách Paris lãng mạn, menu đồ uống thanh lọc detox tốt cho sức khỏe.",
    tags: ["Rooftop", "Trà hoa quả", "Sống ảo", "Cầu Giấy"],
    vibe: ["Hẹn hò", "Check-in", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-43",
    name: "Twitter Beans Coffee - Hoàng Đạo Thúy",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "Tầng 1 Tòa nhà 17T5 Hoàng Đạo Thúy, Trung Hòa, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Twitter+Beans+Coffee+Hoang+Dao+Thuy+Cau+Giay+Ha+Noi",
    rating: 4.3,
    reviewCount: 1178,
    priceRange: "40.000đ - 70.000đ",
    priceLevel: "mid",
    time: "07:00 - 22:00",
    mustTry: "Freeze Matcha kem tuyết / Caramel Macchiato / Bánh Muffin socola",
    review: "Chuỗi cà phê hiện đại quen thuộc của dân công nghệ và văn phòng khu Trung Hòa - Cầu Giấy. Không gian mở nhiều ổ cắm điện, bàn rộng thích hợp học tập và làm việc.",
    tags: ["Làm việc", "Văn phòng", "Matcha", "Cầu Giấy"],
    vibe: ["Làm việc", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-44",
    name: "Aha Coffee - Nguyễn Chánh",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "Số 2 Nguyễn Chánh, Trung Hòa, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Aha+Coffee+Nguyen+Chanh+Cau+Giay+Ha+Noi",
    rating: 4.2,
    reviewCount: 1680,
    priceRange: "25.000đ - 50.000đ",
    priceLevel: "low",
    time: "06:30 - 23:30",
    mustTry: "Cà phê cốt dừa / Nâu lắc / Trà quất mật ong",
    review: "Phong cách cà phê vỉa hè đường phố rộng rãi, bàn ghế gỗ thấp thoải mái. Địa điểm tụ tập chém gió buổi sáng và buổi tối của cư dân khu Cầu Giấy.",
    tags: ["Vỉa hè", "Rộng rãi", "Chém gió", "Cầu Giấy"],
    vibe: ["Vỉa hè", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-45",
    name: "The Coffee House - Cầu Giấy",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "122 Cầu Giấy, Quan Hoa, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=The+Coffee+House+122+Cau+Giay+Ha+Noi",
    rating: 4.3,
    reviewCount: 2450,
    priceRange: "42.000đ - 69.000đ",
    priceLevel: "mid",
    time: "07:30 - 22:30",
    mustTry: "Trà đào cam sả / Cà phê sữa đá / Trà sữa Mắc Ca trân châu trắng",
    review: "Không gian kính sáng sủa, bàn dài trang bị ổ điện đầy đủ phục vụ học tập và chạy deadline. Đồ uống chuẩn vị đồng đều, nhân viên thân thiện.",
    tags: ["Học tập", "Chạy deadline", "Trà đào", "Cầu Giấy"],
    vibe: ["Làm việc", "Học tập"],
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-46",
    name: "Fika Cafe - Nguyễn Phong Sắc",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "50 Nguyễn Phong Sắc, Dịch Vọng Hậu, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Fika+Cafe+Nguyen+Phong+Sac+Cau+Giay+Ha+Noi",
    rating: 4.5,
    reviewCount: 465,
    priceRange: "35.000đ - 65.000đ",
    priceLevel: "low",
    time: "07:30 - 22:30",
    mustTry: "Fika Cold Brew / Trà bưởi hồng nha đam / Bánh Croissant",
    review: "Phong cách Bắc Âu Scandinavian tối giản tinh tế. Không gian yên tĩnh nhiều cây xanh, thích hợp cho các buổi gặp gỡ đối tác và làm việc cá nhân.",
    tags: ["Scandinavian", "Yên tĩnh", "Làm việc", "Cầu Giấy"],
    vibe: ["Làm việc", "Yên tĩnh"],
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-47",
    name: "Chusa Tea & Coffee - Lê Đại Hành",
    category: "cafe-chill",
    district: "Hai Bà Trưng",
    address: "18 Lê Đại Hành, Lê Đại Hành, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Chusa+Tea+Coffee+Le+Dai+Hanh+Ha+Noi",
    rating: 4.6,
    reviewCount: 520,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "08:00 - 22:30",
    mustTry: "Trà sữa Ô Long nướng kem cheese / Trà xoài nha đam / Cà phê sữa",
    review: "Chuyên dòng trà Đài Loan nguyên lá ủ lạnh đậm đà kết hợp lớp kem cheese béo ngậy mằn mặn khó cưỡng. Không gian hiện đại, sạch sẽ.",
    tags: ["Trà sữa Đài Loan", "Kem cheese", "Hai Bà Trưng"],
    vibe: ["Tụ tập bạn bè", "Ăn vặt"],
    image: "https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-48",
    name: "Cafe Nhà Sàn - Bưởi",
    category: "cafe-chill",
    district: "Thanh Xuân",
    address: "Ngõ 462 Đường Bưởi / Hoàng Hoa Thám, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cafe+Nha+San+Duong+Buoi+Ha+Noi",
    rating: 4.5,
    reviewCount: 840,
    priceRange: "30.000đ - 55.000đ",
    priceLevel: "low",
    time: "08:00 - 23:00",
    mustTry: "Cà phê phin bắp / Trà hoa quả khô / Rượu ngô Tây Bắc",
    review: "Ngôi nhà sàn gỗ người Mường nguyên bản được mang về dựng giữa lòng Hà Nội. Ngập tràn đồ cổ, tác phẩm nghệ thuật và không gian văn hóa bản địa độc nhất vô nhị.",
    tags: ["Nhà sàn Mường", "Văn hóa", "Độc lạ", "Hà Nội"],
    vibe: ["Độc lạ", "Chill", "Nghệ thuật"],
    image: "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "cafe-49",
    name: "Trill Rooftop Cafe - Hei Tower",
    category: "cafe-chill",
    district: "Thanh Xuân",
    address: "Tầng 26 Tòa nhà Hei Tower, 1 Ngụy Như Kon Tum, Thanh Xuân, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Trill+Rooftop+Cafe+Hei+Tower+Thanh+Xuan+Ha+Noi",
    rating: 4.3,
    reviewCount: 3250,
    priceRange: "55.000đ - 110.000đ",
    priceLevel: "high",
    time: "08:00 - 23:00",
    mustTry: "Trill Mojito nhiệt đới / Trà hoa quả nhiệt đới / Cà phê kem tươi",
    review: "Tổ hợp cafe rooftop tầng 26 lộng gió với hồ bơi vô cực ngoài trời ngắm toàn cảnh thành phố từ trên cao. Cực kỳ lung linh và lãng mạn khi lên đèn về đêm.",
    tags: ["Rooftop tầng 26", "Hồ bơi", "View toàn cảnh", "Thanh Xuân"],
    vibe: ["Check-in", "Hẹn hò", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-50",
    name: "Nola Cafe - Mã Mây",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "89 Mã Mây, Hàng Buồm, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Nola+Cafe+89+Ma+May+Ha+Noi",
    rating: 4.5,
    reviewCount: 760,
    priceRange: "35.000đ - 65.000đ",
    priceLevel: "low",
    time: "10:00 - 23:30",
    mustTry: "Cocktail Nola / Trà quế gừng / Cà phê phin sữa đặc",
    review: "Căn gác xép bí mật đầy chất thơ giữa phố cổ Mã Mây với mái che bằng những chiếc ô rực rỡ sắc màu. Điểm hẹn ấm cúng và đầy tính nghệ thuật.",
    tags: ["Mái ô sắc màu", "Gác xép", "Phố Cổ", "Hoàn Kiếm"],
    vibe: ["Hẹn hò", "Chill", "Check-in"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: false
  },

  // =========================================================================
  // 🍜 CÁC QUÁN ĂN ĐẶC SẢN NỔI TIẾNG HÀ NỘI
  // =========================================================================
  {
    id: "place-1",
    name: "Phở Gia Truyền Bát Đàn",
    category: "mon-soi",
    district: "Hoàn Kiếm",
    address: "49 Bát Đàn, Cửa Đông, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Pho+Gia+Truyen+Bat+Dan+49+Bat+Dan+Ha+Noi",
    rating: 4.8,
    reviewCount: 6520,
    priceRange: "55.000đ - 85.000đ",
    priceLevel: "mid",
    time: "06:00 - 10:00 & 18:00 - 20:30",
    mustTry: "Phở Tái Nạm + Quẩy giòn chấm nước dùng",
    review: "Nước dùng trong, ngọt thanh từ xương ống bò ninh kỹ chứ không hề lạm dụng mì chính. Thịt bò tươi xắt mỏng tái mềm, nạm giòn thơm.",
    tags: ["Ăn sáng", "Phố Cổ", "Đặc sản Hà Nội", "Xếp hàng"],
    vibe: ["Truyền thống", "Ăn nhanh", "Gia đình"],
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-2",
    name: "Bún Chả Hương Liên (Bún Chả Obama)",
    category: "mon-soi",
    district: "Hai Bà Trưng",
    address: "24 Lê Văn Hưu, Phan Chu Trinh, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Bun+Cha+Huong+Lien+24+Le+Van+Huu+Ha+Noi",
    rating: 4.6,
    reviewCount: 8240,
    priceRange: "50.000đ - 70.000đ",
    priceLevel: "mid",
    time: "08:00 - 20:30",
    mustTry: "Combo Bún chả đặc biệt + Nem hải sản giòn rụm",
    review: "Chả viên và chả miếng nướng than hoa thơm lừng, thịt tẩm ướp đậm đà vừa miệng. Nước chấm chua ngọt hài hòa, nem cua bể vỏ giòn tan.",
    tags: ["Bún chả", "Nổi tiếng", "Khách du lịch", "Hai Bà Trưng"],
    vibe: ["Truyền thống", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-4",
    name: "Xôi Yến Nguyễn Hữu Huân",
    category: "com-xoi",
    district: "Hoàn Kiếm",
    address: "35B Nguyễn Hữu Huân, Lý Thái Tổ, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Xoi+Yen+35B+Nguyen+Huu+Huan+Ha+Noi",
    rating: 4.5,
    reviewCount: 5420,
    priceRange: "40.000đ - 70.000đ",
    priceLevel: "mid",
    time: "06:00 - 23:00",
    mustTry: "Xôi xéo gà xào nấm + Thịt kho trứng ốp",
    review: "Hạt xôi vàng óng, dẻo mềm thơm mùi nếp cái hoa vàng, đậu xanh bào mịn như tơ, rưới thêm chút mỡ hành thơm ngậy và hành phi giòn tan.",
    tags: ["Xôi xéo", "Ăn đêm", "Phố Cổ", "Đậm đà"],
    vibe: ["Ăn nhanh", "Gia đình"],
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-5",
    name: "Phở Cuốn Chinh Thắng - Ngũ Xã",
    category: "banh-mi-cuon",
    district: "Ba Đình",
    address: "7 Mạc Đĩnh Chi, Trúc Bạch, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Pho+Cuon+Chinh+Thang+7+Mac+Dinh+Chi+Ha+Noi",
    rating: 4.7,
    reviewCount: 2810,
    priceRange: "60.000đ - 120.000đ",
    priceLevel: "mid",
    time: "09:00 - 22:00",
    mustTry: "Phở cuốn thịt bò + Phở chiên phồng sốt bò cải",
    review: "Bánh phở mềm dẻo cuốn trọn thịt bò xào lăn thơm phức cùng rau sống thanh mát chấm nước mắm chua ngọt. Đặc biệt phở chiên phồng vàng rụm.",
    tags: ["Phở cuốn", "Phở chiên phồng", "Ba Đình", "Hồ Trúc Bạch"],
    vibe: ["Tụ tập bạn bè", "Gia đình"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-6",
    name: "Lẩu Ếch Dũng Béo - Lò Đúc",
    category: "lau-nuong",
    district: "Hai Bà Trưng",
    address: "338 Lò Đúc, Đống Mác, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Lau+Ech+Dung+Beo+338+Lo+Duc+Ha+Noi",
    rating: 4.7,
    reviewCount: 1620,
    priceRange: "150.000đ - 220.000đ / người",
    priceLevel: "high",
    time: "10:30 - 14:00 & 17:00 - 23:30",
    mustTry: "Nồi lẩu ếch măng cay + Ếch xào chua ngọt + Da ếch chiên giòn",
    review: "Thịt ếch tươi rói được xào sơ ngấm đượm sốt tỏi ớt vàng ươm, săn chắc ngọt thịt. Nước lẩu nấu măng cay bùng nổ vị giác ngày se lạnh.",
    tags: ["Lẩu ếch", "Măng cay", "Nhậu ngon", "Tụ tập"],
    vibe: ["Tụ tập bạn bè", "Nhậu đêm"],
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-19",
    name: "Bít Tết Ba Duy - Vạn Bảo",
    category: "do-a-au",
    district: "Ba Đình",
    address: "105N3, Ngõ 34 Phố Vạn Bảo, Ngọc Hà, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Bit+Tet+Ba+Duy+105N3+Ngo+34+Van+Bao+Ba+Dinh+Ha+Noi",
    rating: 4.8,
    reviewCount: 574,
    priceRange: "80.000đ - 150.000đ / người",
    priceLevel: "mid",
    time: "07:00 - 21:30",
    mustTry: "Bít tết bò chảo gang sốt bơ tỏi / tiêu đen + Bánh mì giòn rụm + Salad dưa chuột",
    review: "Quán bít tết lâu năm rất nổi tiếng ở khu Vạn Bảo. Thịt bò tươi mềm ngọt ngấm sốt đậm đà thơm nức trên chảo gang nóng xèo xèo, ăn kèm pate béo ngậy.",
    tags: ["Bít tết", "Chảo gang", "Vạn Bảo", "Ba Đình", "Ăn no"],
    vibe: ["Gia đình", "Tụ tập bạn bè", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-51",
    name: "Hôm Nào Cà Phê - Nghĩa Tân",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "Số 10, Ngõ 82 Nghĩa Tân, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.app.goo.gl/6tZVVFBjiER63saQ6",
    rating: 4.7,
    reviewCount: 380,
    priceRange: "30.000đ - 60.000đ",
    priceLevel: "low",
    time: "07:00 - 23:00",
    mustTry: "Cà phê cốt dừa béo ngậy / Trà đào cam sả / Cà phê sữa truyền thống",
    review: "Quán cafe sân vườn xanh mát ngập tràn ánh sáng và cây xanh, không gian ấm cúng mộc mạc thích hợp học tập, làm việc hoặc hẹn hò bạn bè.",
    tags: ["Không gian xanh", "Sân vườn", "Nghĩa Tân", "Cầu Giấy", "Học tập"],
    vibe: ["Chill", "Học tập", "Sống ảo"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-52",
    name: "Tiny Cafe | Sky Garden - Nguyễn Ngọc Vũ",
    category: "cafe-chill",
    district: "Cầu Giấy",
    address: "Tầng 19A, 169 Nguyễn Ngọc Vũ, Trung Hòa, Cầu Giấy, Hà Nội",
    mapsUrl: "https://maps.app.goo.gl/7EiDn2UFfG2RaUKt5",
    rating: 4.6,
    reviewCount: 520,
    priceRange: "35.000đ - 60.000đ",
    priceLevel: "low",
    time: "07:30 - 23:00",
    mustTry: "Cà phê trứng béo ngậy / Trà đào cam sả / Bạc xỉu cốt dừa",
    review: "Quán cafe rooftop view sân vườn trên cao cực chill tại tầng 19A Nguyễn Ngọc Vũ. Không gian thoáng đãng ngắm trọn hoàng hôn và thành phố lên đèn, đồ uống đa dạng cùng phong cách vintage xinh xắn.",
    tags: ["Rooftop", "Sky Garden", "Nguyễn Ngọc Vũ", "Cầu Giấy", "View đẹp"],
    vibe: ["Rooftop", "Hẹn hò", "Check-in"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-53",
    name: "Annamoi - Trà & Cà Phê Thủ Công",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "21 - 23 Hàng Bún, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.app.goo.gl/gaAeA84PQxP5qx5T8",
    rating: 4.8,
    reviewCount: 320,
    priceRange: "35.000đ - 65.000đ",
    priceLevel: "low",
    time: "08:00 - 22:30",
    mustTry: "Cà phê muối béo ngậy / Trà thủ công ủ lạnh / Cà phê pha phin truyền thống",
    review: "Không gian vintage nhiều cây xanh thoáng đãng, đồ uống pha chế thủ công đậm đà. Nổi bật với cà phê muối thơm béo ngậy và các loại trà hoa quả thủ công thanh mát.",
    tags: ["Cà phê muối", "Trà thủ công", "Hàng Bún", "Ba Đình", "Vintage"],
    vibe: ["Chill", "Không gian xanh", "Specialty"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "cafe-54",
    name: "Phiên - Quán Nước Ba Đình",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "19 P. Ngọc Hà, Đội Cấn, Ba Đình, Hà Nội 100000",
    mapsUrl: "https://share.google/mdakP1vlj2ipJGPZR",
    rating: 4.8,
    reviewCount: 450,
    priceRange: "30.000đ - 55.000đ",
    priceLevel: "low",
    time: "07:30 - 22:30",
    mustTry: "Trà thảo mộc thanh nhiệt / Cà phê cốt dừa / Nước ép hoa quả tươi",
    review: "Quán nước không gian mộc mạc, yên tĩnh và rất chill nằm ngay phố Ngọc Hà gần Bảo tàng Hồ Chí Minh. Đồ uống thanh mát, giá cả bình dân và nhân viên thân thiện.",
    tags: ["Quán nước", "Ngọc Hà", "Ba Đình", "Yên tĩnh", "Check-in"],
    vibe: ["Yên tĩnh", "Mộc mạc", "Bình dân"],
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    featured: true
  }
];

const DISTRICTS = [
  "Tất cả quận",
  "Hoàn Kiếm",
  "Ba Đình",
  "Hai Bà Trưng",
  "Đống Đa",
  "Cầu Giấy",
  "Tây Hồ",
  "Thanh Xuân"
];

// Profile tác giả / Curator
const DEFAULT_PROFILE = {
  name: "Hanoi Food & Cafe Guide",
  handle: "@foodie_hanoi",
  bio: "Cẩm nang ẩm thực & 50 quán cà phê, đồ uống chọn lọc tại Hà Nội. Đạt chuẩn đánh giá >= 4.0★ và số lượt review chính xác từ Google Maps! 🥢☕✨",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
  socials: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    tiktok: "https://tiktok.com",
    threads: "https://threads.net"
  },
  stats: {
    placesCount: INITIAL_PLACES.length,
    cities: "Hà Nội",
    verified: true
  }
};
