/**
 * Food & Cafe Guide - Hanoi Edition
 * Dữ liệu quán ăn & quán cà phê tuyển chọn tại Hà Nội
 */

const INITIAL_CATEGORIES = [
  {
    id: "all",
    name: "Tất cả",
    icon: "🍽️",
    description: "Tất cả quán ăn & cà phê trong cẩm nang",
    count: 0
  },
  {
    id: "mon-soi",
    name: "Món sợi (Phở, Bún, Mì)",
    icon: "🍜",
    description: "Phở bò truyền thống, bún chả, bún riêu, miến lươn chuẩn vị Hà Thành",
    mapsUrl: "https://www.google.com/maps/search/pho+bun+mien+ha+noi"
  },
  {
    id: "com-xoi",
    name: "Cơm & Xôi",
    icon: "🍚",
    description: "Xôi xéo thơm nức, cơm rang dưa bò, cơm tấm sườn nướng",
    mapsUrl: "https://www.google.com/maps/search/xoi+com+ha+noi"
  },
  {
    id: "banh-mi-cuon",
    name: "Bánh mì & Đồ cuốn",
    icon: "🥖",
    description: "Bánh mì phố cổ, phở cuốn Ngũ Xã, bánh cuốn nóng hổi",
    mapsUrl: "https://www.google.com/maps/search/banh+mi+pho+cuon+ha+noi"
  },
  {
    id: "lau-nuong",
    name: "Lẩu & Nướng",
    icon: "🥩",
    description: "Lẩu ếch măng cay, nướng ngói vỉa hè, lẩu riêu cua bắp bò",
    mapsUrl: "https://www.google.com/maps/search/lau+nuong+ha+noi"
  },
  {
    id: "cafe-chill",
    name: "Cà phê & Trà",
    icon: "☕",
    description: "Cafe view đẹp, cafe trứng truyền thống, góc học tập & làm việc chill",
    mapsUrl: "https://www.google.com/maps/search/cafe+chill+ha+noi"
  },
  {
    id: "an-vat",
    name: "Ăn vặt & Tráng miệng",
    icon: "🍧",
    description: "Nộm bò khô, nem chua rán, chè khúc bạch, tào phớ thanh mát",
    mapsUrl: "https://www.google.com/maps/search/an+vat+ha+noi"
  },
  {
    id: "do-a-au",
    name: "Đồ Nhật, Hàn & Á Âu",
    icon: "🍣",
    description: "Sushi tươi ngon, mì cay Hàn Quốc, pizza nướng củi, steak",
    mapsUrl: "https://www.google.com/maps/search/nha+hang+nhat+han+ha+noi"
  },
  {
    id: "quan-nhau",
    name: "Quán nhậu & Đêm",
    icon: "🍻",
    description: "Bia hơi vỉa hè, nhậu lai rai, ẩm thực phố đêm không ngủ",
    mapsUrl: "https://www.google.com/maps/search/quan+nhau+bia+dem+ha+noi"
  }
];

const INITIAL_PLACES = [
  {
    id: "place-1",
    name: "Phở Gia Truyền Bát Đàn",
    category: "mon-soi",
    district: "Hoàn Kiếm",
    address: "49 Bát Đàn, Cửa Đông, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Pho+Gia+Truyen+Bat+Dan+49+Bat+Dan+Ha+Noi",
    rating: 4.8,
    priceRange: "55.000đ - 85.000đ",
    priceLevel: "mid", // low (<50k), mid (50k-150k), high (>150k)
    time: "06:00 - 10:00 & 18:00 - 20:30",
    mustTry: "Phở Tái Nạm + Quẩy giòn chấm nước dùng",
    review: "Nước dùng trong, ngọt thanh từ xương ống bò ninh kỹ chứ không hề lạm dụng mì chính. Thịt bò tươi xắt mỏng tái mềm, nạm giòn thơm. Điểm trừ là luôn phải xếp hàng tự bưng bê nhưng hương vị hoàn toàn xứng đáng!",
    tags: ["Ăn sáng", "Phố Cổ", "Đặc sản Hà Nội", "Xếp hàng"],
    vibe: ["Truyền thống", "Ăn nhanh", "Gia đình"],
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-2",
    name: "Bún Chả Hương Liên (Bún Chả Obama)",
    category: "mon-soi",
    district: "Hai Bà Trưng",
    address: "24 Lê Văn Hưu, Phan Chu Trinh, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Bun+Cha+Huong+Lien+24+Le+Van+Huu+Ha+Noi",
    rating: 4.6,
    priceRange: "50.000đ - 70.000đ",
    priceLevel: "mid",
    time: "08:00 - 20:30",
    mustTry: "Combo Bún chả đặc biệt + Nem hải sản giòn rụm",
    review: "Chả viên và chả miếng nướng than hoa thơm lừng, thịt tẩm ướp đậm đà vừa miệng. Nước chấm chua ngọt hài hòa, đu đủ xanh giòn sần sật. Nem cua bể vỏ giòn tan, nhân đầy đặn.",
    tags: ["Bún chả", "Nổi tiếng", "Khách du lịch", "Hai Bà Trưng"],
    vibe: ["Truyền thống", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-3",
    name: "Cafe Đinh (Cà Phê Trứng)",
    category: "cafe-chill",
    district: "Hoàn Kiếm",
    address: "13 Đinh Tiên Hoàng, Hàng Bạc, Hoàn Kiếm, Hà Nội (Tầng 2)",
    mapsUrl: "https://maps.google.com/?q=Cafe+Dinh+13+Dinh+Tien+Hoang+Ha+Noi",
    rating: 4.9,
    priceRange: "25.000đ - 40.000đ",
    priceLevel: "low",
    time: "07:00 - 21:30",
    mustTry: "Cà phê trứng nóng / Cacao trứng",
    review: "Quán nằm trên gác 2 một căn nhà cổ view nhìn thẳng ra Hồ Gươm. Lớp kem trứng đánh bông mịn như nhung, ngọt béo thơm lừng không một chút mùi tanh kết hợp cùng cà phê Robusta đậm đặc ấm nóng.",
    tags: ["Cafe trứng", "View Hồ Gươm", "Cổ kính", "Giá rẻ"],
    vibe: ["Chill", "Hẹn hò", "Check-in"],
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-4",
    name: "Xôi Yến Nguyễn Hữu Huân",
    category: "com-xoi",
    district: "Hoàn Kiếm",
    address: "35B Nguyễn Hữu Huân, Lý Thái Tổ, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Xoi+Yen+35B+Nguyen+Huu+Huan+Ha+Noi",
    rating: 4.5,
    priceRange: "40.000đ - 70.000đ",
    priceLevel: "mid",
    time: "06:00 - 23:00",
    mustTry: "Xôi xéo gà xào nấm + Thịt kho trứng ốp",
    review: "Hạt xôi vàng óng, dẻo mềm thơm mùi nếp cái hoa vàng, đậu xanh bào mịn như tơ, rưới thêm chút mỡ hành thơm ngậy và hành phi giòn tan. Topping thịt kho mềm tan ngập sốt đậm đà.",
    tags: ["Xôi xéo", "Ăn đêm", "Phố Cổ", "Đậm đà"],
    vibe: ["Ăn nhanh", "Gia đình"],
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-5",
    name: "Phở Cuốn Chinh Thắng - Ngũ Xã",
    category: "banh-mi-cuon",
    district: "Ba Đình",
    address: "7 Mạc Đĩnh Chi, Trúc Bạch, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Pho+Cuon+Chinh+Thang+7+Mac+Dinh+Chi+Ha+Noi",
    rating: 4.7,
    priceRange: "60.000đ - 120.000đ",
    priceLevel: "mid",
    time: "09:00 - 22:00",
    mustTry: "Phở cuốn thịt bò + Phở chiên phồng sốt bò cải",
    review: "Bánh phở mềm dẻo cuốn trọn thịt bò xào lăn thơm phức cùng rau sống thanh mát chấm nước mắm chua ngọt. Đặc biệt phở chiên phồng vàng rụm giòn rụm bên ngoài, ngấm đẫm sốt thịt bò cải xào sền sệt cực đã.",
    tags: ["Phở cuốn", "Phở chiên phồng", "Ba Đình", "Hồ Trúc Bạch"],
    vibe: ["Tụ tập bạn bè", "Gia đình"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-6",
    name: "Lẩu Ếch Dũng Béo - Lò Đúc",
    category: "lau-nuong",
    district: "Hai Bà Trưng",
    address: "338 Lò Đúc, Đống Mác, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Lau+Ech+Dung+Beo+338+Lo+Duc+Ha+Noi",
    rating: 4.7,
    priceRange: "150.000đ - 220.000đ / người",
    priceLevel: "high",
    time: "10:30 - 14:00 & 17:00 - 23:30",
    mustTry: "Nồi lẩu ếch măng cay + Ếch xào chua ngọt + Da ếch chiên giòn",
    review: "Thịt ếch tươi rói được xào sơ ngấm đượm sốt tỏi ớt vàng ươm, săn chắc ngọt thịt. Nước lẩu nấu măng cay chua chua cay cay bùng nổ vị giác, nhúng rau muống giòn sần sật ăn giữa ngày se lạnh Hà Nội là chuẩn bài.",
    tags: ["Lẩu ếch", "Măng cay", "Nhậu ngon", "Tụ tập"],
    vibe: ["Tụ tập bạn bè", "Nhậu đêm"],
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-7",
    name: "Yên Cafe (Quán Cà Phê Yên Quán Thánh)",
    category: "cafe-chill",
    district: "Ba Đình",
    address: "184 Quán Thánh, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Yen+Cafe+184+Quan+Thanh+Ha+Noi",
    rating: 4.8,
    priceRange: "35.000đ - 55.000đ",
    priceLevel: "low",
    time: "07:30 - 18:00",
    mustTry: "Sapa (Cà phê sữa tươi thơm ngậy) / Katabata / Vàng Nắng",
    review: "Không gian nhỏ xinh, mộc mạc đậm chất Hà Nội. Dòng cà phê Arabica phối Robusta rang thơm nức, món 'Sapa' với sữa béo thanh tao ngọt dịu là chân ái của tín đồ mê cà phê hiện đại.",
    tags: ["Cafe ngon", "Sapa Yên", "Vỉa hè chill", "Quán Thánh"],
    vibe: ["Chill", "Hẹn hò", "Làm việc"],
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-8",
    name: "Bánh Mì 25 - Hàng Cá",
    category: "banh-mi-cuon",
    district: "Hoàn Kiếm",
    address: "25 Hàng Cá, Hàng Đào, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Banh+Mi+25+25+Hang+Ca+Ha+Noi",
    rating: 4.8,
    priceRange: "35.000đ - 50.000đ",
    priceLevel: "low",
    time: "07:00 - 21:00",
    mustTry: "Bánh mì thập cẩm pate bơ thịt nguội + Bánh mì bò phô mai",
    review: "Vỏ bánh mì luôn được nướng nóng giòn tan, pate nhà làm béo thơm mịn màng kết hợp rau dưa nộm thanh mát không hề ngấy. Nhân viên thân thiện, phục vụ nhanh.",
    tags: ["Bánh mì", "Phố Cổ", "Giá rẻ", "Take-away"],
    vibe: ["Ăn nhanh", "Chill"],
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-9",
    name: "Nộm Bò Khô Long Vi Toàn - Hàng Giầy",
    category: "an-vat",
    district: "Hoàn Kiếm",
    address: "25 Hàng Giầy, Hàng Buồm, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Nom+Bo+Kho+Long+Vi+Toan+25+Hang+Giay+Ha+Noi",
    rating: 4.6,
    priceRange: "35.000đ - 50.000đ",
    priceLevel: "low",
    time: "09:00 - 22:30",
    mustTry: "Đĩa nộm bò khô thập cẩm + Bánh bột lọc chiên/hấp",
    review: "Đĩa nộm đầy đặn với đu đủ xanh bào sợi giòn sần sật, thịt bò khô, gân bò dẻo quẹo, lá lách bùi bùi và lạc rang thơm phức. Nước giấm chua ngọt pha cực kỳ khéo.",
    tags: ["Nộm bò khô", "Ăn vặt", "Hàng Giầy", "Phố Cổ"],
    vibe: ["Ăn vặt", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-10",
    name: "Bún Ốc Sườn Cô Sáu",
    category: "mon-soi",
    district: "Hai Bà Trưng",
    address: "254 Lạc Trung, Vĩnh Tuy, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Bun+Oc+Suon+Co+Sau+254+Lac+Trung+Ha+Noi",
    rating: 4.7,
    priceRange: "40.000đ - 65.000đ",
    priceLevel: "low",
    time: "06:30 - 14:00 & 17:00 - 22:00",
    mustTry: "Bún ốc sườn dẻ + Ốc nhồi giòn béo + Quẩy giòn",
    review: "Nước dùng chua thanh đậm đà từ dấm bỗng nếp thơm phức, thêm chút ớt chưng cay nồng xuýt xoa. Sườn dẻ ninh nhừ mềm thơm róc thịt, ốc nhồi to béo giòn sần sật đã miệng.",
    tags: ["Bún ốc", "Sườn dẻ", "Dấm bỗng", "Hai Bà Trưng"],
    vibe: ["Ăn sáng", "Ăn trưa", "Truyền thống"],
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-11",
    name: "Bánh Cuốn Nóng Bà Hoành",
    category: "banh-mi-cuon",
    district: "Hai Bà Trưng",
    address: "66 Tô Hiến Thành, Bùi Thị Xuân, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Banh+Cuon+Ba+Hoanh+66+To+Hien+Thanh+Ha+Noi",
    rating: 4.6,
    priceRange: "40.000đ - 60.000đ",
    priceLevel: "low",
    time: "06:00 - 20:00",
    mustTry: "Bánh cuốn chả quế nướng than + Cà cuống",
    review: "Bánh cuốn tráng mỏng tang mịn màng, rắc hành phi tự phi vàng giòn thơm nức mũi. Chả quế và thịt nướng than hoa thơm lừng chấm cùng nước mắm ấm nóng gia truyền thanh ngọt.",
    tags: ["Bánh cuốn", "Tô Hiến Thành", "Gia truyền", "Ăn sáng"],
    vibe: ["Truyền thống", "Gia đình"],
    image: "https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-12",
    name: "Chả Cá Thăng Long - Đường Thành",
    category: "mon-soi",
    district: "Hoàn Kiếm",
    address: "19-21-2D Đường Thành, Cửa Đông, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Cha+Ca+Thang+Long+19+Duong+Thanh+Ha+Noi",
    rating: 4.7,
    priceRange: "180.000đ - 250.000đ / người",
    priceLevel: "high",
    time: "10:30 - 21:30",
    mustTry: "Suất Chả cá Lăng xào thì là hành hoa + Mắm tôm đánh sủi bọt",
    review: "Thịt cá lăng lọc xương thái miếng vuông vắn, tẩm nghệ vàng ươm nướng thơm rồi đảo trực tiếp trên chảo dầu cùng hành hoa, thì là. Ăn kèm bún rối, lạc rang và mắm tôm đánh chanh ớt sủi bọt dậy mùi.",
    tags: ["Chả cá Lăng", "Đặc sản Hà Nội", "Sang trọng", "Phố Cổ"],
    vibe: ["Gia đình", "Tiếp khách", "Hẹn hò"],
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-13",
    name: "Nem Chua Rán Tạm Thương",
    category: "an-vat",
    district: "Hoàn Kiếm",
    address: "Ngõ Tạm Thương, Hàng Gai, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Nem+Chua+Ran+Ngo+Tam+Thuong+Hang+Gai+Ha+Noi",
    rating: 4.6,
    priceRange: "30.000đ - 60.000đ",
    priceLevel: "low",
    time: "08:30 - 23:00",
    mustTry: "Khay nem chua rán giòn rụm + Khoai tây chiên bơ tỏi + Trà chanh",
    review: "Ngõ nhỏ đậm chất Hà Nội phố cổ. Nem rán vỏ ngoài giòn rụm, bên trong dẻo dai bùi béo, chấm tương ớt cay ngọt xè lưỡi, nhâm nhi cùng đĩa xoài dầm củ đậu chống ngấy.",
    tags: ["Nem chua rán", "Ngõ Tạm Thương", "Ăn vặt phố cổ", "Tuổi thơ"],
    vibe: ["Ăn vặt", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-14",
    name: "Bia Hơi Hải Xồm - Tăng Bạt Hổ",
    category: "quan-nhau",
    district: "Hai Bà Trưng",
    address: "22 Tăng Bạt Hổ, Phạm Đình Hổ, Hai Bà Trưng, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Bia+Hai+Xom+22+Tang+Bat+Ho+Ha+Noi",
    rating: 4.5,
    priceRange: "120.000đ - 200.000đ / người",
    priceLevel: "mid",
    time: "09:30 - 23:00",
    mustTry: "Bia hơi Hà Nội lạnh có bọt + Bò xào măng trúc + Lạc luộc",
    review: "Nơi trải nghiệm văn hóa bia hơi Hà Nội đích thực! Bia rót từ cốc thủy tinh xanh xù xì đặc trưng mát rượi, đồ nhắm phong phú từ đậu lướt ván giòn vỏ ruột mềm, mực nướng đến dê tái chanh.",
    tags: ["Bia hơi Hà Nội", "Quán nhậu", "Sôi động", "Vỉa hè"],
    vibe: ["Nhậu đêm", "Tụ tập bạn bè"],
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-15",
    name: "Maison de Éte - Cafe Tone Kem Hàn Quốc",
    category: "cafe-chill",
    district: "Đống Đa",
    address: "Ngõ 4B Đặng Văn Ngữ, Trung Tự, Đống Đa, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Maison+de+Ete+Dang+Van+Ngu+Ha+Noi",
    rating: 4.7,
    priceRange: "45.000đ - 65.000đ",
    priceLevel: "low",
    time: "09:00 - 21:00",
    mustTry: "Trà đào cam sả thảo mộc + Bánh sừng bò nướng mật ong",
    review: "Không gian xinh xắn tone gỗ sáng và kem trắng chuẩn style Hàn Quốc, ánh sáng tự nhiên tuyệt đẹp cho các bạn thích chụp ảnh sống ảo. Đồ uống thanh mát, bánh ngọt tươi mỗi ngày.",
    tags: ["Cafe Hàn Quốc", "Check-in", "Đặng Văn Ngữ", "Sống ảo"],
    vibe: ["Hẹn hò", "Chill", "Check-in"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-16",
    name: "Pizza 4P's - Phan Kế Bính",
    category: "do-a-au",
    district: "Ba Đình",
    address: "5 Phan Kế Bính, Cống Vị, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Pizza+4Ps+Phan+Ke+Binh+Ha+Noi",
    rating: 4.9,
    priceRange: "200.000đ - 350.000đ / người",
    priceLevel: "high",
    time: "10:00 - 22:30",
    mustTry: "Pizza 4 Phô mai kèm mật ong + Mì Ý cua sốt kem cà chua",
    review: "Phô mai tươi Burrata tự làm béo ngậy khó cưỡng. Đế pizza mỏng nướng lò củi giòn viền thơm nức. Không gian thiết kế tinh tế, phục vụ chuẩn Nhật Bản chu đáo từng chi tiết.",
    tags: ["Pizza 4P's", "Phô mai Burrata", "Hẹn hò sang xịn", "Đồ Âu"],
    vibe: ["Hẹn hò", "Gia đình", "Tiếp khách"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    featured: true
  },
  {
    id: "place-17",
    name: "Manwah Taiwanese Hotpot - Giảng Võ",
    category: "lau-nuong",
    district: "Ba Đình",
    address: "Tầng 2 Grandeur Palace, 138B Giảng Võ, Ba Đình, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Manwah+Giang+Vo+Ha+Noi",
    rating: 4.8,
    priceRange: "350.000đ - 490.000đ / người",
    priceLevel: "high",
    time: "11:00 - 22:00",
    mustTry: "Nước lẩu Mala Đài Loan cay tê + Bò Wagyu nhúng + Quầy kem tráng miệng",
    review: "Nước lẩu đậm đà các loại thảo mộc thơm phức, thịt bò nhập khẩu tươi mềm, quầy line tráng miệng và kem xịn sò không giới hạn. Rất thích hợp cho những buổi tiệc gia đình và liên hoan.",
    tags: ["Lẩu Đài Loan", "Buffet", "Giảng Võ", "Cao cấp"],
    vibe: ["Tụ tập bạn bè", "Gia đình", "Tiếp khách"],
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80",
    featured: false
  },
  {
    id: "place-18",
    name: "Chè Bốn Mùa - Hàng Cân",
    category: "an-vat",
    district: "Hoàn Kiếm",
    address: "4 Hàng Cân, Hàng Đào, Hoàn Kiếm, Hà Nội",
    mapsUrl: "https://maps.google.com/?q=Che+Bon+Mua+4+Hang+Can+Ha+Noi",
    rating: 4.7,
    priceRange: "20.000đ - 35.000đ",
    priceLevel: "low",
    time: "09:00 - 23:00",
    mustTry: "Chè sen long nhãn + Khúc bạch thanh mát + Sủi dìn nóng",
    review: "Quán chè cổ truyền hàng chục năm tuổi ở phố cổ. Hạt sen ninh bở tơi ngọt bùi, nhãn lồng giòn ngọt, nước đường thơm dịu hoa nhài thoang thoảng. Mùa đông có bánh trôi tàu và sủi dìn nóng hổi.",
    tags: ["Chè truyền thống", "Phố Cổ", "Hàng Cân", "Giải khát"],
    vibe: ["Ăn vặt", "Truyền thống", "Chill"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    featured: false
  }
];

const DISTRICTS = [
  "Tất cả quận",
  "Hoàn Kiếm",
  "Ba Đình",
  "Hai Bà Trưng",
  "Đống Đa",
  "Cầu Giấy",
  "Tây Hồ",
  "Thanh Xuân"
];

// Profile tác giả / Curator
const DEFAULT_PROFILE = {
  name: "Hanoi Food & Cafe Guide",
  handle: "@foodie_hanoi",
  bio: "Cẩm nang ẩm thực & cà phê chọn lọc tại Hà Nội. Review chân thực, đánh giá vị trí Google Maps và mẹo gọi món ngon nhất định phải thử! 🥢✨",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
  socials: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    tiktok: "https://tiktok.com",
    threads: "https://threads.net"
  },
  stats: {
    placesCount: INITIAL_PLACES.length,
    cities: "Hà Nội",
    verified: true
  }
};

